### ISSUE TITLE
Change used timezone from UTC to local one

### ISSUE THREAD

**Issue by CoLuxe** [eikek/docspell#1052]
It seems like Docspell uses the UTC time instead of the local time set on system level. So the timestamps for Mails and the Update Checker are not in time.
Im using the Java Packages.

**Comment by eikek** [comment]
Yes, this is true :/ I'm still not sure how to solve this. It is not only UTC on the server, but the client also has no notion of different time zones.

**Comment by CoLuxe** [comment]
Maybe running a little lightweight NTP tool that catches the local time after starting?

**Comment by eikek** [comment]
Getting the timezone from the server (of the current user) is not a problem. But this only uses another timezone, that is again good for some users and bad for others. It might be a start, though, since it is a personal tool and people usually control the server. But I'd rather have it as a user setting maybe.

**Comment by arittner** [comment]
Maybe this should be a user-config: Timezone, to recalculate the UTC from backend to the local time of the user.
