### ISSUE TITLE
Support Encrypted/Signed PDFs

### ISSUE THREAD

**Issue by seijikun** [eikek/docspell#1074]
Some PDFs are encrypted without password, meaning that everyone can open & read them, but you can't change them.

OCRMyPDF detects such PDFs, but does not attempt to decrypt them (see https://github.com/jbarlow83/OCRmyPDF/issues/223).
Instead, it aborts with exit code `8` (see: https://github.com/jbarlow83/OCRmyPDF/blob/fc75254c603620557b30fe3e5a80feba1ba280d2/src/ocrmypdf/exceptions.py#L21), and an error message suggests decrypting the PDF using the `qpdf` tool before trying again:
```
EncryptedPdfError: Input PDF is encrypted. The encryption must be removed to perform OCR.
For information about this PDF's security use
   qpdf --show-encryption infilename
You can remove the encryption using
   qpdf --decrypt [--password=[password]] infilename
```
An example of such a PDF can be found [here](https://www.telekom.de/dlp/agb/pdf/46510.pdf).
Interestingly, docspell generates a proper preview-image for the file, but opening it with ViewerJS results in an empty gray window and error messages in the console.

Would it be possible to support such files?

**Comment by eikek** [comment]
Ah thanks! I'll see how to support these files. Since they are not really encrypted, it should be possible. Another idea is to have a list of password somewhere and go through them for encrypted pdfs.

**Comment by eikek** [comment]
I just tried this file and docspell can actually process it. OcrMyPDF fails, but the other mechanisms work and text is extracted etc.

It's "only" that viewerjs cannot display it, but the browser (tried firefox and chromium) can. I was about to open an issue at viewerjs, but since it hasn't received any changes for several years now, I guess it's not worth it. I probably need to find something else to display pdf files in the browser in the near future :/

But I think an option to decrypt a pdf like this one is also good to have as well as to decrypt PDFs where users know the password. Of course, it's again a bit ugly, since the passwords need to be in the config file and/or database.

**Comment by seijikun** [comment]
Thank you very much!
I was wondering why you were using ViewerJs in general. Wouldn't it be much easier to use the [HTML5 <embed>](https://www.w3schools.com/TAGs/tag_embed.asp) tag? No dependencies, native browser functionality.
Like:

```html
<html style="height: 100%;">
    <body style="height: 100%;">
        <h1>The embed element</h1>
        <embed type="application/pdf" src="https://www.telekom.de/dlp/agb/pdf/46510.pdf" style="width: 100%; height: 100%">
    </body>
</html>
```

**Comment by eikek** [comment]
Ah interesting, I was wondering why you were using viewerjs :). The viewerjs only exits for platforms where the browser is not able to render pdfs. And sadly this is on most mobile devices. This is also the reason why it is enabled by default. On desktop systems, where you have a "real" browser, you always can check this box and it will be rendered by the browser. If you get a download dialog, it might not be able to display the pdf? Which browser are you using?

**Comment by seijikun** [comment]
I am using `Firefox 94.0a1 (nightly)` with some addons. But the browser itself is not the problem.
I just tested a new and clean Firefox profile without addons, and there the native functionality works just as expected. I will investigate!
