### ISSUE TITLE
dsc export in docker container

### ISSUE THREAD

**Issue by mtettke123** [eikek/docspell#1259]
Hi,

in the moment, I'm testing docspell and paperless-ng and try to compare all the different features. While docspell is much more feature rich and has the better lookint interface (just imho), the paperless way of storing files is very appealing to me, as I can directly sync them to my owncloud and have them availiable and backuped in more than one way.

One way to work around this, could be the `dsc export` for me. The idea here could be, to periodically export the database and sync this export (just an idea). But trying to export gives me:

```
/opt/export # dsc export --all --date-links --target /opt/export/
Cmd: Export: An http error occurred: Session error: Error reading session file at /root/.config/dsc/dsc-token.json: No such file or directory (os error 2)
```

I can't find anything regarding this in the [documentation](https://docspell.org/docs/tools/cli/#export-data). Is this a bug or do I need to specify additional parameters?

Edit: I found the "login" command, but this gives me:

```
/home # dsc login -u testuser --password testpass
Cmd: Login: An http error occurred: An error was received from http://localhost:7880/api/v1/open/auth/login: error sending request for url (http://localhost:7880/api/v1/open/auth/login): error trying to connect:able (os error 99)
```

which seems strange, as "localhost" is the container "consumedir" (running docspell/dsc:latest). Am I using the wrong container? But docspell/restserver:latest does not have dsc:

```
/opt # dsc
/bin/sh: dsc: not found
```

I'm sure I've overlooked something...

**Comment by eikek** [comment]
Hi @mtettke123 ,

thanks for your interest and asking here. The project is missing some user friendliness especially in the documentation and also in error messages in `dsc`. I'm always glad when it's pointed out, because I often don't see it :-).

The `dsc export` command was created for this purpose: to have a periodic job export all your data to a format outside of the application. Glad you found the login command. The error message should be improved to give a hint to it, sorry for the confusion! The first error occurs, because the dsc tool needs to authenticate and tries to look up a token from a file. This token is created when running `dsc login`.

One advantage with this approach (using `dsc export`) is, that you also backup the metadata (all the tags and stuff that was manually added). Another approach (simpler, but less flexible) is to restrict yourself in only using some directory for adding files. This directory can be watched, docspell doesn't send files twice, so you can freely organize it. Then this directory is the "source" and can be backed up. Of course, files uploaded otherwise are then lost, it might be fine if you are the only user - just depends on the situation. I would use the `export` way, because it is more independent.

Now to the problem: _TL;DR_: When in the `consumedir` container, you need to specify the url where dsc should connect to. You can do this via the `-d` option or write it in a config file. You can run `dsc --help` to find more about it. _Explanation_: The `dsc` tool is an extrenal command line tool which acts as a http client to the docspell server. So it can run on any machine that has a connection to the docspell server. This is often useful, when you want to run the periodic backup or upload command on a different machine/container etc. When you use dsc in a docker container, you need now to make sure that the docspell server is reachable from that container. So `localhost` won't work, because it points to the container that has `dsc` installed, but there is nothing running here. Fixing it depends on your setup. If you use the provided docker-compose setup you can reach the docspell server via `http://docspell-restserver:7880` from the `consumedir` container (you can see it in the `docker-compose.yml` file that starts dsc for uploading files). This is because docker-compose creates a network with all defined containers "in it". The `docspell/restserver` container doesn't have `dsc` installed, that's right (its not necessary). 

It now depends on what you want/how you want it in order to find a setup for your situation. For example: if you want to run the periodic backup on the same machine (I'm assuming you use the provided docker-compose setup), I would probably define another container that runs this command periodically, something like this (you can copy the consumedir container definition and adopt it):

```yml
  backup:
    image: docspell/dsc:latest
    container_name: docspell-backup
    command:
      - watch
      - -n
      - 86400
      - dsc login -u user -p pass && dsc -d "http://docspell-restserver:7880" export --all --date-links --target /opt/backup
    restart: unless-stopped
    volumes:
      - ./backup:/opt/backup
    depends_on:
      - restserver
```
(not tested! just to serve as an idea, you can also create your own container containing your config and backup script)

But if your backup drive is in another machine, you can copy the dsc tool to that machine and use a cron job or systemd timer to achieve the same thing without the docker overhead. 

On another note: I would always recommend to do database backups as well. It is only one command and it can be very easily restored; and it is independent from docspell. I added some notes [here](https://docspell.org/docs/install/docker/#backups) as well. If you backup the images and the db, you can always recreate the current setup, even if docspell should be gone.
The output of the export command can currently not be imported, because there is no functionality yet. It serves as a way to get all your data into the filesystem and to provide a somewhat nicer view if you access it via filemanagers or expose it via samba/nfs.

**Comment by mtettke123** [comment]
Hi @eikek ,

thank you so much for the explanation, this all makes sense. I'm planning to do complete database backups once productive, but I would like to also export the documents regularly to have them available outside of docspell and available in my owncloud which is synced to my local computers. I like this flexibility. 
Using the import dir for such purpose doesn't work for me, as I want to be able to add files through different sources without loosing them in the export. Again, I like the flexibility.

My problem is, that `dsc login` doesn't seem to allow the -d flag:
```
/opt # dsc login -d "http://docspell-restserver:7880" -u testuser --password testpass
error: Found argument '-d' which wasn't expected, or isn't valid in this context
```

Can you help me with this one? `dsc login --help` doesn't list -d. If I'm not logged in, I cant use export, as far as I understood.

Thanks again!

**Comment by eikek** [comment]
Ah yes, again something to better document. If you run `dsc --help` it shows you the options to the main command (`dsc`) and sub commands. The `-d` is an option to the main command (it is a global option). The `login` is a subcommand and has its own options. So it's: `dsc -d … login -u …`. It's right that you need to be logged in. There is a way using a config file to make it non-interactive.

**Comment by mtettke123** [comment]
Hi @eikek ,

this works, thank you:
```
dsc -d "http://docspell-restserver:7880" login -u testuser --password testpass
dsc -d "http://docspell-restserver:7880" export --all --date-links --folder-links --tag-links --link-naming name --target /opt/export/
```

Are there any other options to "link-naming" than "name"? I can't find anything in the documentation.

A far as I can see, when rerunning the export, already exported files are not exported again/overwritten, although the output lists them again? That would be great, cause giving them a new timestamp would trigger a new sync in owncloud. So far so good.

Is there any way to alter the export scheme? Perfect for me would be an order by correspondent (`--correspondent-links` does not exist, yet, correct?), ideally followed by another subdir "document type" (something like this does not exist in docspell, right?

My final dream would be something configurable like in paperless-ng: 
`
FILENAME_FORMAT: "{correspondent}/{document_type}/{created_year}-{created_month}-{created_day} {title}"
`
Sorry for having so many questions in one discussion - and thank you SO much for your help!

**Comment by mtettke123** [comment]
by the way: I like the idea of having just the `dsc` executable on my owncloud-Server. This would simplify the synchronisation.

**Comment by eikek** [comment]
> Are there any other options to "link-naming" than "name"? I can't find anything in the documentation.

No, only `id` or `name` currently. It can be seen via `dsc export --help`. 

> A far as I can see, when rerunning the export, already exported files are not exported again/overwritten, although the output lists them again? That would be great, cause giving them a new timestamp would trigger a new sync in owncloud. So far so good.

Yes exactly - the idea is that existing files are not overwritten, but this can be changed with `--overwrite`.

> Is there any way to alter the export scheme? Perfect for me would be an order by correspondent (`--correspondent-links` does not exist, yet, correct?), ideally followed by another subdir "document type" (something like this does not exist in docspell, right?

The option `--correspondent-links` exists. There is no dedicated thing for "document type" in docspell, correct. The idea is to use tags and tag categories. So I myself have a tag category "document type" and all tags in this category (like invoice, contract etc) are marking the document type. You can filter for tag categories as well.

> My final dream would be something configurable like in paperless-ng: `FILENAME_FORMAT: "{correspondent}/{document_type}/{created_year}-{created_month}-{created_day} {title}"`

That would be really nice, indeed! It is currently not possible. We can create a ticket for this, but it's likely not happening soon - simply due to lack of time on my end.  So PRs are welcome, ofc 😄 (code is [here](https://github.com/docspell/dsc)). It is possible to create something like this in the `dsc` tool; the document type could then be written like `{category:document-type}` meaning that a tag of that category is used in this place.

> Sorry for having so many questions in one discussion - and thank you SO much for your help!

Oh, no worries - you're welcome!

**Comment by mtettke123** [comment]
Hi and thanks so much,

seems in some points I was just to dumb to read the documentation correctly. Sorry for this.

Having a short look at the code, I don't think I will be able to add anything valuable soon. I'm not really a coder, and this seems much to complex for me in the moment. So I have created [a feature request](https://github.com/eikek/docspell/issues/1262), more to write my ideas down - and who knows, maybe sometime...

**Comment by eikek** [comment]
Hi and no worries! The PR thing was not meant to you in particular - just in general and for communicating expectations. Thanks a lot for your feature request! I'm sure it will be addressed at some point, but no "eta".

**Comment by eikek** [comment]
I'm closing this here, the bad error message mentioned above is now tracked in docspell/dsc#118
