### ISSUE TITLE
Can we install on windows 

### ISSUE THREAD

**Issue by ShriakntPilaware** [eikek/docspell#1307]
How can we install  this application to windows 
Kindly send me the process  and which DB we can use for this

**Comment by eikek** [comment]
Hi @ShriakntPilaware - I don't have windows so I can't confirm what comes next; I never tried it. 

This _should_ work like on Linux: one way is to use the zip files, unzip them with your tool of choice and execute the `bat` file inside the `bin/` folder (as described [here](https://docspell.org/docs/install/download-run/)). But running on windows means to change lots of configured tools or make them available in your path (like tesseract or wkhtmltopdf, see [here](https://docspell.org/docs/install/prereq/)), Otherwise if docker is a thing in windows you can use the docker images. The database is again your choice. If you have a PostgreSQL or MariaDB running somewhere you can use them (recommended). I have no clue how to install those on windows. You can use the H2 database, this should work since it is only using the filesystem. Using docker might be the more convenient option. Oh and I think you could also try [nix](https://nixos.org/download.html#nix-install-windows).
