### ISSUE TITLE
Can't log in on remote server

### ISSUE THREAD

**Issue by Kiskadee-dev** [eikek/docspell#1369]
I have the same issue as #250 and #285 but the docspell.conf doesn't seem to exist now, so i'm really not sure about how to change the localhost only setting so i can use a .local domain instead

Installed with docker-compose, no .env or any other configuration file

**Comment by eikek** [comment]
If you only want to use a different domain, you don't need to adjust anything actually. Can you share more details about the error?

Regarding the config file: The `docspell.conf` file is not there, because the `docker-compose.yml` file contains a set of environment variables to configure. You can look [here](https://docspell.org/docs/configure/#environment-variables) for a list of possible options. But you can still create a config file instead and pass it to the command - for that you also need to edit the `docker-compose.yml` file: you would need to mount the file into the container and give its path to the command.

**Comment by Kiskadee-dev** [comment]
Hey, thanks for the reply! I'll try binding the actual address using the env vars! but i'll also point the source of my confusion so hopefully others don't get stuck at this.

My use case is that I want a server to handle the documents of the house, so remote devices (within the network) should be able to create new accounts and login.

As for the error, it happens when you try to create a new account from a remote device, only on the browser, nothing on the terminal logs. 

I'm accessing the server with a hostname, in this case docspell.local:7880

![image](https://user-images.githubusercontent.com/10299707/153737867-151c70a7-7487-474f-88af-136461fc6ead.png)


I've just checked if I can actually create a new account from the server, with the localhost:7880, and I can't, same error happens, the account is created but I can't login.

**Comment by Kiskadee-dev** [comment]
Ok, forgive me, I did not realise the Collective name should be exactly the same as the username, this solved the problem!

**Comment by eikek** [comment]
Hi @Kiskadee-dev no worries! Yes these errors are a bit confusing, but they are currently "normal". A 403 means that you are not logged in. The client tries some requests on start, realises it doesn't work and redirects to the login page. Interesting are the errors immediately after you click the "login" button (you can clear all entries before you click it).

Regarding the collective name vs user name: they don't need to be equal. But if they are not equal, you must specfiy both - otherwise docspell wouldn't know who to login. For example, if your collective is named `family` and one user is named `max` your login name must be `family/max`. But if collective and user are equal, you can omit one part and use `family` instead of the redundant form `family/family`. The docs have a section about it [here](https://docspell.org/docs/#collective).
