### ISSUE TITLE
consumedir alternative for mounted NFS drives

### ISSUE THREAD

**Issue by rklueber** [eikek/docspell#137]
Hello,

I am stunned by your solution. It works really well. Thank you for providing this.

The last puzzle piece missing is `consumedir`. I have an NFS drive on a NAS were the PDFs from my scanner arrive. This drive is mounted via NFS on the host (which is a VM running under proxmox). This dir where the NFS is munted is a volume inside the container which runs `consumedir`.

`inotify` is not working with files on an NFS drive. What are my options to get the PDFs arriving on the NAS automatically show up inside docspell?

I am really looking forward to solve this last puzzle.

Regards
Ralf

**Comment by rklueber** [comment]
A simple solution is to run a cronjob on the host every 5min. Seems to work.

**Comment by eikek** [comment]
Hi @rklueber 
first, thanks for your kind words! That is really motivating.

Using inotify with NFS mounts is not possible. I think it's the same with other network based filesystems, like CIFS. A workaround would be to poll periodically as you mentioned. This is of course not a nice solution, but would work if it's not super urgent.

Another one could be to install the `consumedir.sh` script at the machine/container where the scanner stores the files. Then there is no NFS mount so inotify would work. Instead of mounting all files over the network, you would let the consumedir script upload each new one to docspell at another machine. This is how my setup works at home. You can, of course, mount it anyways for other things, the point is only to let the `consumedir.sh` run on the host containing the "real" filesystem. Would this work with your setup?

**Comment by eikek** [comment]
Hello @rklueber, do you think there is anything I can help you with here? I don't think I can do something to make `consumedir.sh` work on nfs, maybe there is some other solution (than inotify), but I simply don't know. I then would close this issue wdyt?

**Comment by eikek** [comment]
Hi @rklueber , I close this ticket now. But feel free to reopen it if you have further ideas/questions or just create new issues. Thanks.
