### ISSUE TITLE
Skip OCR on documents that already have searchable text

### ISSUE THREAD

**Issue by andreklug** [eikek/docspell#1374]
Hi @eikek 
First I would like to express how much I like docspell from what I have tested in the past days. I have been using Alfresco in the last years, only for it's full text search and will happily ditch it for docspell.

Because of that, I have a few thousand documents I would like to feed into docspell. All of them have been OCR'ed already, also the page orientation is done. My impression is that docspell doesn't look if a PDF has searchable text already and therefore does process every document again. Is that observation correct? If so, it would be super helpful to have that check performed automatically or maybe an option to deactivate the OCR and PDF optimization.

Another thing, is it possible to dedicate more resources at the OCR and optimization? Docspell runs in a VM with plenty of cores assigned, but a brief look into htop gave me the impression that only a single core is being used?

Thank you!

**Comment by eikek** [comment]
Hi @andreklug 

thank you for the kind words. I think your points can be addressed. I think it's good to look through the [default configuration](https://docspell.org/docs/configure/#joex) for joex to see what can be adjusted.

- OCR: Docspell by default first strips the text of any PDF and only if it's length is below some configurable amount (`min-text-len`), it will try OCR in order to see if that results in more. So if all your PDFs already contain the text, it is very likely that it will not run OCR again. You can configure this amount and set it to 0 and it will never do OCR for PDFs. Another note in that regard is that docspell by default converts PDFs into PDF/A using `ocrmypdf`, which has its own settings. You can adjust the command or simply disable it if you don't need it.
- Resources: Yes, this is definitely possible. The single core is just the default setting. If you have a strong machine, you can set a higher `pool-size` (also in the linked config above) and it will process documents in parallel. You could also add more machines: they need to connect to the same database and have different `app-id`s. 

If you use the docker-compose setup, all these settings can be set using environment variables. But you can also create a configuration file and feed it to the process.
