### ISSUE TITLE
Concerning Person: different name variants and also the family

### ISSUE THREAD

**Issue by andreklug** [eikek/docspell#1375]
Hi @eikek 

I really like the concept of the concerning person. While testing the first documents I was under the impression that I would have to set up different persons for the different ways my Name (Andre vs André vs A. and some silly Andrè) is written on incoming correspondence. Of course, this breaks the usability of the concerning person. As I am still starting with docspell, is this figured out autmatically? Otherwise it would be useful to be able to define one (ore more) "Alias" name of a person.

How is a family handled? There are docs addressed to "Fam", "Fam." or "Familie", which include then also my wife as a concerning person. It doesn't look like that's possible, but would be great to set up a hierarchy which then optionally would allow to include anything addressed to the family when I am looking for conversation.

Thank you, 
a(.)ndr(e|é|è)

**Comment by eikek** [comment]
The concerning person is limited to be a single person. The "familiy" cannot be modeled via the concerned person, I'm afraid. You could fallback to tags for this or add a "fake" concerned person "Familie" … not very nice but could do the job.

There are feature requests to allow to set multiple concerned persons, but this is quite a large change and won't happen anytime soon. I don't think you should add different persons that are the same person in real life - this can get quite confusing. But at the end, it must work for you.

Person candidates are found in two ways. First it looks what NLP has found in a text and if a name is matched against a name from your concerned persons it will be considered. It will first try the longest names and fallback to shorter ones. But I don't think it will consider "A." to be a name, so I think only a "A." in a document won't have any effect here (there is also a minimum length required, otherwise there are too many results). However, it could find persons where a short version of their name is in a document. Secondly, there is a classifier trained with the current (sub)set of documents. This should actually find (figuratively) that documents with "André  and "Andre" in it have always been associated to the same concerned person (how it is really spelled doesn't matter here). After some time, most patterns that can be deduced from the text should be guessed quite well. But I can't tell for sure :). It works quite well for my documents so far.

Something you could try out is to add emails or websites to a person, because these are considered when looking for matches. Maybe your documents contain these as well?

It might be a good thing to add aliases to persons and organizations to store different spellings. But this also opens up for false positives.

**Comment by andreklug** [comment]
Thank you for your comprehensive answer!
