### ISSUE TITLE
Documents with German non-ASCII characters (äöüß etc.) are OCRd with wrong encoding.

### ISSUE THREAD

**Issue by Jost-Philip** [eikek/docspell#1662]
Hi!
I have noticed a strange behavior in my new docspell installation which I cannot quite explain.
Recently I uploaded about four year's worth of phone bills written in German by Deutsche Telekom into docspell, about 40 documents total. Since these documents are obviously automatically generated, they all look pretty much the same, with the exception of the due date and the charged amount mostly. All source documents are vector PDFs (all-digitally rendered, not printed/scanned!).
They all render fine on any PDF viewer I tried, including docspell.

All these invoice documents contain the phrase "Freundliche Grüße".

On about 50% of the documents, both the text overlay on docspell's internal reader and the full-text-search result snippet show this correctly.
![image](https://user-images.githubusercontent.com/8749900/180651891-51caa2a0-4aa3-48cd-a8f8-c8c53115790c.png)

On the other 50%, there are obvious encoding errors in the phrase, the kind you get when you try to interpret unicode text as 8859/1 or Latin1:
![image](https://user-images.githubusercontent.com/8749900/180651492-f7ef806f-4ace-4970-8515-462911aea0e7.png)

It does not seem to have anything to do with the document age (seen this on an invoice from 2018 and one from 2022, but several in between were fine!). All documents were automatically imported as eMail attachments.

Any ideas?

docspell 0.37 on current raspberry Pi OS (64bit), installed natively through apt-get and ZIP files. (no docker), running on Raspberry Pi 4b 8GB.

**Comment by Snify89** [comment]
Depending on the joex settings/configuration, Docspell tries first to fetch the already (ORCd) text given in the pdf.

If the fetched amount/length is lesser than the value in the configuration (DOCSPELL_JOEX_EXTRACTION_PDF_MIN__TEXT__LEN=500), it is OCRed again and finally the larger text is applied to the Fulltext content search. 

You may also change the language settings.

I have had no issues and I don't think this is an E-Mail issue but a configuration issue, which can improve your output.

Maybe some PDFs are wrongly OCRed already and are then applied.

Try to troubleshoot like this:
- Inspect the original (untouched) PDF (and it's OCR data). Use a browser, select all text and paste it somewhere.
- Upload/import (E-Mail) the PDF to Docspell and inspect the queue log files and see, if ocrmypdf, tesseract, etc. is executed and which text is applied and what parameters are used. 
- Post the results here and we can see/give better advice on what's going on

**Comment by Jost-Philip** [comment]
I did some more digging and find your assessment to be generally 
correct. The wrongly encoded text is present in the original document 
already.
So this is clearly not a bug, but a result of poor quality input 
data.Hurray for companies who still can't do PDF properly in 2022!

Unfortunately I still have to deal with this for my documents somehow, 
and since I think your defaults for docspell make a lot of sense most of 
the time, I think it's best to deal with it on a per-document basis.

Since you obviously have a lot of experience in manipulating PDFs: do 
you have any suggestions on how to best remove the garbage text layer 
from documents? I know "Print as image" to PDF-printer usually works, 
but it often massively increases file size and is quite cumbersome to 
set up...



Feature suggestion:
add a checkbox/button to docspell's "reprocess this document" button on 
the document details page, to allow for ditching any sort of text that 
is associated with the document and re-OCRing the document as image.


Thanks for your quick support! I've been using docspell for two weeks 
and am already loving it!

**Comment by Snify89** [comment]
I had the same issue.
Some (most actually) of my documents were poorly OCRed and I had to deal with this.
In general, Docspell always keeps the original file, which is good.

Also, Docspell already has a button for re-processing an item (attachment). 
![image](https://user-images.githubusercontent.com/5088625/180729873-2751af86-dca0-4330-86b5-81420374d1dc.png)

I would not remove the OCR layer at all, since this takes time, space, etc. and is actually not productive at all.


These are the steps on how Docspell deals with PDF files:

1. Docspell receives a(ny) PDF file and keeps this as the original file, just as is.

2. Docspell uses ocrmypdf to convert the PDF to a PDF/A file.
NOTE: If the original PDF has already an OCR layer, it will keep the layer just as is.
If no OCR layer has been found, ocrmypdf will use tesseract (OCR the PDF) AND adds the OCR Layer to the PDF/A file.
Tesseract/OCRMyPDF will respect your language settings from Docspell (i.e. German)

3. You now have a PDF/A File with either your original OCR layer or the new layer from ocrmypdf/tesseract
(ocrmypdf uses tesseract)

4. The PDF/A file is now your original file with the default ".converted" suffix.

5. Now it's time to get the text from the converted PDF/A file:
Docspell gets all the text from the OCR Layer. (using pdfbox)

6. Now Docspell will fetch the value from the configuration:
DOCSPELL_JOEX_EXTRACTION_PDF_MIN__TEXT__LEN
( https://docspell.org/docs/configure/defaults/#:~:text=of%20text%20extraction-,extraction,-%7B%0A%20%20%20%20%23%20For%20PDF%20files )

7. If the extracted text (length) from the PDF/A file is lesser/shorter than the value min-text-len,
Docspell will run full tesseract on the PDF/A file (no OCR layer is added/overwritten) (again),
and uses/inserts the text to the database for content search.
So here, the results from the tesseract can slightly vary than the text from the OCR layer of the PDF/A file.
If the extracted text is larger than the configuration value, it uses just the OCR layer from the PDF/A and uses this for content search.

8. Your document is ready in docspell.

So depending on your needs here are your options:
(Keep in mind, the original is always present and available in Docspell)

1. You want a clean converted PDF/A File (.converted), with a clean OCR layer and use the text from the layer for content search.
2. You don't care about the OCR Layer in your PDF/A file, but you want a clean content search (at least)

The first option requires you to modify the ocrmypdf command parameter like this in your joex config:

```
convert {
                ocrmypdf = {
                  enabled = true
                  command = {
                        program = "ocrmypdf"
                        args = [
                          "-l", "{{lang}}",
                          "--force-ocr",
                          "--deskew",
                          "--tesseract-timeout=999999",
                          "--clean",
                          "-j", "1",
                          "{{infile}}",
                          "{{outfile}}"
                        ]
                        timeout = "30 hours"
                  }
                }

extraction {

        pdf {
                min-text-len = 1
        }

```

This will ensure, that a good/new/clean PDF/A file is available to download and uses the the clean OCR layer.


The second option is just to use this in your joex config:

```
extraction {

        pdf {
                min-text-len = 0
        }
```

This will keep everything as it is, but the content search is clean - yet the PDF file may have a faulty OCR layer.

Hope this helps

**Comment by eikek** [comment]
Maybe we can also add the option to change the extracted text, so it will be fixed for content search at least (the option 1 above). The feature suggestion would also be possible (to ditch existing text layers and always use ocr) - as it is very similar to the config option `pdf.min-text-len = 0`, if I understood correctly.

**Comment by Jost-Philip** [comment]
I tried your suggestion 1 from above and it served my purposes well.

When writing the above comment, I wasn't fully thinking about that docspell creates its own version of the document, while still keeping the original file. I can happily live with just the converted version containing the 'good' OCR layer, because that is usually the file I see and interact with in docspell. In fact, this is even better than my original suggestion, because it gives me one good, 'clean' version to display and work with in docspell and in all my records, and at the same time I still have the original  available just the way it came, should anyone ever need to see it for what ever reason.

So, problem solved, user happy! Thank you very much for your support!

On a side note: I do understand that docspell already has a button for re-processing a document. However, if I understand correctly this button will always re-process the document using the default settings from the config file.
While this is certainly useful to have when processing failed for whatever temporary reason (libreOffice not installed properly, ocrmypdf ran out of memory,...) or after the defaults changed, I recognize that the rather extreme preferences postulated above might be overkill for a collection where the vast majority of input data is clean and of good quality.

In such a large, 'good' collection, I wouldn't want to modify the well-balanced global defaults just because for a handful of sub-standard documents processing with these settings doesn't produce the desired results. In this situation, it would be nice to have a second button there that allows for quickly reprocessing just this one hand-selected, poor quality document using much more aggressive settings, but still leaving the defaults as they were.

**Comment by Snify89** [comment]
> I tried your suggestion 1 from above and it served my purposes well.
> 
> When writing the above comment, I wasn't fully thinking about that docspell creates its own version of the document, while still keeping the original file. I can happily live with just the converted version containing the 'good' OCR layer, because that is usually the file I see and interact with in docspell. In fact, this is even better than my original suggestion, because it gives me one good, 'clean' version to display and work with in docspell and in all my records, and at the same time I still have the original available just the way it came, should anyone ever need to see it for what ever reason.
> 
> So, problem solved, user happy! Thank you very much for your support!
> 
> On a side note: I do understand that docspell already has a button for re-processing a document. However, if I understand correctly this button will always re-process the document using the default settings from the config file. While this is certainly useful to have when processing failed for whatever temporary reason (libreOffice not installed properly, ocrmypdf ran out of memory,...) or after the defaults changed, I recognize that the rather extreme preferences postulated above might be overkill for a collection where the vast majority of input data is clean and of good quality.
> 
> In such a large, 'good' collection, I wouldn't want to modify the well-balanced global defaults just because for a handful of sub-standard documents processing with these settings doesn't produce the desired results. In this situation, it would be nice to have a second button there that allows for quickly reprocessing just this one hand-selected, poor quality document using much more aggressive settings, but still leaving the defaults as they were.

Glad it helped :)

I am not sure (haven't tested this actually) about the re-processing but it should use the given joex config values and not the default settings.
To "filter" the (re-)processing, you may override the ocrmydf command entirely with your own script. (just an idea)

Something like this:

```
convert {
                ocrmypdf = {
                  enabled = true
                  command = {
                        program = "/usr/bin/mycustomscript.sh"
                        args = [
                          "{{lang}}",
                          "{{infile}}",
                          "{{outfile}}"
                        ]
                        timeout = "30 hours"
                  }
                }

```

so the script (/usr/bin/mycustomscript.sh) could be like this (not tested, but should give you an idea):

```
#!/bin/bash

# e.g. if document filename ($2) has some pattern.
# you could also extract pdf metadata or some sort to determine "aggressive" processing
if ....
# use "aggressive processing
/usr/bin/ocrmypdf --force-ocr --deskew --tesseract-timeout=999999 --clean -j 1 -l "$1" "$2" "$3"
else
# use default joex processing
/usr/bin/ocrmypdf --skiptext --deskew -j 1 -l "$1" "$2" "$3"
fi
```

be aware of your stdout/stderr and exit code, as docspell might interpret them.

**Comment by eikek** [comment]
I'm closing this. You can now fix the extracted text in the webui if the imported pdf has bad chars.
