### ISSUE TITLE
Rest server dies with mismatched migration

### ISSUE THREAD

**Issue by Kiskadee-dev** [eikek/docspell#1688]
Started my vm today and to my surprise the server is stuck on a loop where it says the migrations are mismatched, the last update was a few months ago and was working fine yesterday so i have no idea why this happened.

![image](https://user-images.githubusercontent.com/10299707/183456930-a973ca6a-fd1f-4c75-9896-c583f63f9fd6.png)
![image](https://user-images.githubusercontent.com/10299707/183457005-90393096-3974-4c98-886d-85d053fc552b.png)
![image](https://user-images.githubusercontent.com/10299707/183457100-d88f9ce6-a9d7-4733-8e61-2a088c61916b.png)

The docker compose is set to the latest, which was updated a month ago, but i'm still on v0.35
![image](https://user-images.githubusercontent.com/10299707/183458567-53cda6eb-53e5-4513-b053-a6472c276ab9.png)

**Comment by eikek** [comment]
Strange - the current latest release is 0.38.0, something with your update procedure didn't work. 

The version 0.35.0 had some problems in the docker images (an incompatible zlib package). This would explain the checksum issues with the migrations. I think it's best to go to 0.36.0 (or any later stable version) - but do a backup of your database before ;-).

**Comment by Kiskadee-dev** [comment]
I've upgraded to 0.36 and added the commands to the .env to attempt a repair, but no luck, still yells the migrations are mismatched and everything catches fire after

![image](https://user-images.githubusercontent.com/10299707/183487959-9b2b6da8-eb27-48ee-9d22-f589ee10f32d.png)

I've added the commands to the .env file and started docker once, not sure if it ran something or if i did something wrong.

I did not attempted an upgrade prior to this, unless something did upgrade by accident but i doubt as i was on 0.35 for months.

I do have a backup from 4 days ago but it would be great to know what broke this so it doesn't break again

**Comment by eikek** [comment]
So, you added these repair-flags and started once? Did this succeed? And if so, does it now startup fine without these repair settings?

I cannot say for sure what the cause is in your case. The reason for the checksum mismatches is a broken zlib library in the docker image (java stdlib calls a C library to create a crc32 checksum). If someone runs docspell 0.35.0 the first time, the checksums are calculated wrong and stored into the database. When upgrading, the checksums are validated and this issue appears. Or, if someone upgrades from a previous version to 0.35.0, then there are existing correct checksums in the db and this issue appears as well. The "repair" flag will tell the migration to ignore the database checksums and update them with the current ones. But if you always have been on 0.35.0, the issue should not happen 🤔 , the images don't change.

I recommend to always do a db dump before upgrading - just in case.

**Comment by Kiskadee-dev** [comment]
Well I've actually updated from an older version to 0.35.0, but a long time ago and have been using it since.

Loaded the backup i said i had but it's also broken for some reason with the same problem, will try loading another later (they're huge).

I'm in doubt if it is really executing the repair as it does the migration but states that the repair flag is false, i've added the repair flags into the .env file but also tried setting it inside the docker-compose file in both joex and rest-server

![env](https://user-images.githubusercontent.com/10299707/184274133-fd4a52a0-746b-41ea-85f8-54658dd1c6ca.png)

![e1](https://user-images.githubusercontent.com/10299707/184274155-5727515b-c0a8-494b-8aba-b5d25f7bc9c1.png)

![e2](https://user-images.githubusercontent.com/10299707/184274165-d6eaacdb-9003-4be7-ab5b-aef03126dd75.png)

![e3](https://user-images.githubusercontent.com/10299707/184274176-aa644c09-97af-4b34-92f5-00d0405fcef9.png)

All of these migrations and no repairs despite setting the .env flags, i'm confused

**Comment by eikek** [comment]
Your backup is fine, it's probably a broken zlib library in a docker image that caused this. 

The repair flag is for some reason not picked up, you could try to define it in the dockerfile itself if not already tried or specify it explicitely via `--env-file`…. Do you use a config file by any chance - or only the env vars? You also need to add it for both components (it's two different env variables and they must be added to the corresponding component).

The logs show that the problem seems to be in the joex image only. You can also disable running the db migrations for joex and let it run only on the restserver (the logs there seem fine). It would be these env vars:

```
DOCSPELL_JOEX_DATABASE__SCHEMA_RUN__FIXUP__MIGRATIONS=false
DOCSPELL_JOEX_DATABASE__SCHEMA_RUN__MAIN__MIGRATIONS=false
```

Or you can try to repair it manually via SQL:
```
update flyway_fixup_history set checksum = 1347412019 where checksum = 1776159438 and version = '1.33.0';
```
My database shows `1347412019` I guess at some previous point the wrong checksum was added to your db - probably as I said caused by a broken zlib library in the docker image.

**Comment by Kiskadee-dev** [comment]
If i let rest-server fix its checksum and set joex to ignore the migration fixup, it works and docspell boots up fine, it looks like the rest-server expects one checksum and joex expects another, then once rest-server fixes the one it expects, joex starts complaining

![image](https://user-images.githubusercontent.com/10299707/184460977-3b07ad8e-27b9-4531-ba7c-b9f2564e489f.png)

As you can see joex expects the checksum that was applied before, the one the rest-server was complaining in the previous screenshots, so when 1347412019 is applied to the database joex is fine but the rest-server dies, if 1776159438 is applied joex dies but the rest-server is alright.

So, when i attempted to set the checksum directly in the database a few fireworks happened

![image](https://user-images.githubusercontent.com/10299707/184461265-09280775-5228-49d1-baaf-7f287a91e9c9.png)
![image](https://user-images.githubusercontent.com/10299707/184461429-f37f37af-8aae-4548-bec3-2c5758977be5.png)


(logged into the postgres container and ran the sql command with psql)

The rest-server also did not like this and also complained about the checksum..

![image](https://user-images.githubusercontent.com/10299707/184462859-6542d65d-48ec-45b8-82ba-f4587adae034.png)


Well, setting joex to ignore the fixups works but i'm not sure if it'll give problems in the future

**Comment by eikek** [comment]
Oh wow, what a mess! This looks as if the docker images of 0.36.0 are not good - just strange that nobody complained when it was released…. I would also try going to the latest release (0.38.0) - the images are always rebuild and contain newer packages.

I cannot understand how that one sql line could change multiple migrations with different values 🤔 … I think the repair did this.

In my database (I don't use docker) the checksum of the fixup migration 1.33.0 is `1347412019` - this is the correct checksum. So I suppose the restserver is the problematic image.

You can safely set joex to ignore the fixups. These have been applied anyways and the correct behavior is then to just skip it. I would still try to update to the latest release. Maybe start one container first and see how it goes and potentially repair the changesets until it starts fine. Then start the other container …

**Comment by Kiskadee-dev** [comment]
Upgraded directly to v0.38.0 and set joex to ignore fixing the migrations, it's working fine! thanks for the help, your project is amazing.
