### ISSUE TITLE
Jobs waiting in the queue

### ISSUE THREAD

**Issue by nnovaes** [eikek/docspell#1692]
Whenever I start a job it sits for a long time in the queue before it runs. Is there any place I can configure for jobs to start immediately, or, if there's some sort of scheduler, for me to decrease the time it takes to poll the queue for a new job?

Even with a single job scheduled this happens. Looking on the documentation it says this should be normal, but I only have one collective so no need for multiple executors.

> "Since job executors are shared among all collectives, it may happen that a job is some time waiting until it is picked up by a job executor. You can always start more job executors to help out."

**Comment by eikek** [comment]
Hi @nnovaes ,

this is probably due to a connectivity issue between the restserver and joex component. How are you running docspell, via docker? The joex component is triggered when a new job is put into the queue, but it also wakes up itself periodically (you can configure it, see [this](https://docspell.org/docs/configure/defaults/#joex) at `scheduler.wakeup-period`). It is triggered by a http call, if this is failing then only the `wakeup-period` is there as a fallback.

Even with one collective, it might be beneficial to have multiple executors if you upload many files. The note you cited is for the case when there are more collectives; then you could see jobs in `waiting` state, because the joex is busy with a job from a different collective. But with only one collective you should see a job running immediately.
