### ISSUE TITLE
No more converted documents

### ISSUE THREAD

**Issue by gandy92** [eikek/docspell#1872]
I just found out, that apparently my docspell installation does no more provide the converted documents. For all documents I have scanned up to Nov.18, there is an associated converted PDF stored with the original document. For the next scanned document from Nov.25, and every other document added since then, the converted file is missing, although the OCR seems to have run fine, since all the suggestions as well as the extracted text are there.

I've grep-ed the docker-compose log for the string "converted" but only found:
```
docspell-joex | 2022.11.19 16:57:08:0004 [io-comp...] [WARN ] docspell.scheduler.impl.LogSink.logInternal:45 - >>> 2022-11-19T15:57:09.064009937Z Warn BJafVpks8.../2/process-item/Low: Cannot extract text: Command `tesseract u-2.tif stdout -l deu` timed out (3300000 ms). Try with converted file (jobId: "BJafVpks8uk-ydZ2N4ztKQ3-CBBpxexfuCo-6ZkgoobsAq3", task: "process-item", group: "2", jobInfo: "BJafVpks8.../2/process-item/Low")
docspell-joex | 2022.11.19 17:47:11:0002 [io-comp...] [WARN ] docspell.scheduler.impl.LogSink.logInternal:45 - >>> 2022-11-19T16:47:11.919823025Z Warn FgBQSuTka.../2/process-item/Low: Cannot extract text: Command `tesseract u-3.tif stdout -l deu` timed out (3300000 ms). Try with converted file (jobId: "FgBQSuTkajo-tCSGCNzEbMr-SFa9Ykgi5FV-hpBBRRP31HU", task: "process-item", group: "2", jobInfo: "FgBQSuTka.../2/process-item/Low")
```
Also, there was no restart of the docspell docker installation, or the host system during the transition between "with converted" and "w/out converted".

I've just rebooted everything and tried to re-process one of the affected documents, which did not yield the converted file.
Then I've scanned one of the affected documents again, with the same result.

@eikek : Do you have any suggestions on how I could debug this further? I was just about to categorise the recently added documents, so I could easily reprocess them without loosing too much work.

**Comment by gandy92** [comment]
Strange, now it's working again - all I did was updating my docker-compose file to use postgres:15.1 instead of 14.1, pulling everything in, starting again with --force-recreate, only to realize that postgres would not start any more complaining about some directory that was created with 14.1 being incompatible with 15.1, changing the postgres version back to 14.1, pulling again, starting up once more with --force-recreate. I then reprocessed one of the affected documents and got the converted document, as it should be.
I'm at a complete loss as to what was happening there, and a bit worried about the 14.1 vs. 15.1 issue.

**Comment by eikek** [comment]
Hi @gandy92 , that is really strange. I doubt, though, that the postgres upgrade is influencing this. The conversion is done by joex using some external tool depending on the input format. The text can be extracted often times from the original file. Maybe simply the reboot helped here, it's hard to say 🤔  When you upgrade postgres to another major version, you need to do a manual data migration (which postgres has docs for). But being on 14.1 is just fine.

If you have the item ids, you can use `curl` to easily to trigger a reprocessing via the api, described here: https://docspell.org/openapi/docspell-openapi.html#tag/Item/operation/sec-item-start-reprocess

You'll need to add the auth token that you could for example just extract from the browser or login via dsc and check the file `~/.config/dsc/dsc-token.json` or just do a login via `curl`. You can look at these [examples](https://docspell.org/docs/api/intro/#examples). If the items are already confirmed, then a re-processing will not change any item metadata - because docspell will not overwrite anything that was confirmed to be correct by a human :-). Only re-processing unconfirmed items could change item metadata. The re-processing will change extracted text, though and possibly other information gathered from the file(s). hth!

**Comment by gandy92** [comment]
Hi @eikek, thank you, I did not know that, but of course it makes perfect sense :-) Hopefully that human (me) can be trusted to have confirmed the right data, in the first place :-)
Thank you again for your assistance!
