### ISSUE TITLE
How to scale joex?

### ISSUE THREAD

**Issue by crane-denny** [eikek/docspell#1902]
I am looking for a way to speed up import processes.
I see an option for joex to have a pool size bigger than one and also an option to increase memory. But I am not sure which one to pick. My best guess right now is by just adding another joex container within the docker-compose file.

But I am open for better options. :)

**Comment by eikek** [comment]
You can use any or all of these options - it depends on what you want to achieve. If you want to increase parallelism in order to process multiple files at once for your installation, I would increase the pool size and maybe the memory accordingly (because now two big files could be processed at the same time). I don't think it makes much sense in general to start multiple containers on the same machine,  but it is still a nice option to temporarily use multiple processors without restarting or interfering the current installation. 

But it is a good option if you can add more machines to support processing. When I imported all my docs in the beginning, I installed joex on all our laptops/desktops so they all helped wtih processing. Now that only a few documents arrive a day, one joex with pool-size=2 is enough for me.

If you want your one joex to be a bit faster, then adding more memory can help (if you had given it a bit too little before).

**Comment by crane-denny** [comment]
Scratch that. I found my error. It's `DOCSPELL_JOEX_SCHEDULER_POOL__SIZE`. :)
