### ISSUE TITLE
Importing emails is stuck

### ISSUE THREAD

**Issue by iszhi** [eikek/docspell#2113]
I imported work emails from the past 4 years. However the number of emails is definitely not as much as 40k. Not sure what went wrong. Now this task runs daily and never seems to run out. What should I do?
![image](https://github.com/eikek/docspell/assets/33443222/3302ff31-6ec9-4304-b571-5639e3e0b52b)

**Comment by eikek** [comment]
The number shows the amount of queued jobs. If it is >40k probably that many jobs have been submitted. Can you give some details about the task that fails/is stuck? Are there logs? How many job executors do you have configured?

**Comment by iszhi** [comment]
@eikek I only have one job executors on my old PC (6300HX+12Gb memory). I just import the last 3 years emails. I think the total number of emails is only up to thounds. Why there are more than 40K jobs submitted? The following showed a stucked job from yesterday.
![image](https://github.com/eikek/docspell/assets/33443222/1d5bae03-c591-4a54-a72d-819a8edc1f34)

**Comment by iszhi** [comment]
Or, is there a way to reset it? or rerun the jobex?

**Comment by eikek** [comment]
Hey @iszhi why there are so many jobs I can't say. Somehow they got submitted. Perhaps something was run multiple times? If there is one executor, one blocking would then block all others as well. The logs indicate that some HTML->PDF conversion was not successful. Are there any really large files being processed? You could try the `weasyprint` command manually to see what the errors are. The jobs take very long, perhaps due to large files and not a very strong machine. But eventually the original file can be downloaded from the webui. 

Unfortunately, there is no realy way to clear the whole job queue. But you can cancel any job from the webui. Those not already started will be removed from the queue. You can also stop docspell and I can give you a SQL statement to delete all jobs if you like.

**Comment by iszhi** [comment]
@eikek, Recently, I got time to see my library again. I realized that all jobs were finished actually. I'm able to upload new documents into the library. The only problem is that the item number should be 0 instead of  54608. 
![image](https://github.com/eikek/docspell/assets/33443222/c73c9d02-81dc-4a7e-8c87-638fbbf2424f)
