### ISSUE TITLE
Unable to login from another computer

### ISSUE THREAD

**Issue by eliluong** [eikek/docspell#212]
I'm able to log into the application via the browser running locally on the machine docspell is installed on. When I try to log in from another computer, the login page shows up, but I can't log in.

I saw in the terminal: `docspell-restserver | [blaze-selector-2] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /192.168.0.177:57118`

But in Chrome inspector (on another computer), I see:
```
Failed to load resource: net::ERR_CONNECTION_REFUSED localhost:7880/api/v1/sec/folder?q=:1 
Failed to load resource: net::ERR_CONNECTION_REFUSED localhost:7880/api/v1/sec/tag?q=:1 
Failed to load resource: net::ERR_CONNECTION_REFUSED docspell.js:15 
Remove account from local storage
Failed to load resource: net::ERR_CONNECTION_REFUSED localhost:7880/api/v1/open/auth/login:1 
```

Is something wrong with my configuration? Thanks.

**Comment by eikek** [comment]
Yes, maybe the config is wrong for this case. The `base-url` setting is wrong. It must be the external url  (as you write in your browser), because the app creates external links and must know the external url to itself. I suspect, that you have a `base-url` of `http://localhost:7880` (the default)? Then try to change it to `http://192.168.x.y:7880` where `x.y` is the last part of the external ip of the machine running docspell.

**Comment by eikek** [comment]
There is a little documentation [here](https://docspell.org/docs/configure/#baseurl) – if you think it can be improved, please tell me or adopt the text:-) Maybe a few more words could be added to the [Running](https://docspell.org/docs/install/running/) section regarding this case…?

**Comment by eliluong** [comment]
Thanks @eikek, that worked. I had to edit `docspell/docker/docspell.conf` instead of `docspell.server` like your documentation said. I've seen other docker packages get it to work without having to edit this URL in so I assume there's probably a way to do this.

**Comment by eikek** [comment]
Oh yes, I mean the section in the config file is `docspell.server` (because there is another `base-url`).

Do you have any pointers to such a package that works without this setting? I don't want to rely on "tricks" like reading the host header (in case of an reverse proxy) or the browser url in the client. But if there is a nice way, I'd use it of course.

**Comment by eliluong** [comment]
I've tried another document management package called Teedy (https://github.com/sismics/docs), they offer a pre-built docker image to pull from online and it works out of the box with regards to the IP address issues. It wasn't what I wanted for document management, so going to try out your software!

**Comment by eikek** [comment]
Thank you for the hint! I'll take a look to learn from them. If your issue is solved, I'd close this issue? (Currently, one has to change this setting in order to make it work across machines)
