### ISSUE TITLE
Login causes flood of sessions

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2292]
After I log in, Docspell goes into a bit of a tornado, and will attempt to "add account to local storage" (from browser console) multiple times a second:

![image](https://github.com/eikek/docspell/assets/195073/5718b9ff-e88e-4f42-81e6-f1a8f2fe7231)

These are calls to `/api/v1/sec/auth/session`, causing the auth cookie and also the `account` data in local storage to change every time, as a new token is received. And megabytes of data to be transferred within minutes.

There is no way to stop this, other than to close the tab.

**Comment by madduck** [comment]
Even deleting the user and collective from the database has no effect. Here is how Nekron on described it on Matrix/Gitter:

> Looks to me like the frontend UI is caching your logged in state and never calls the logout endpoint to invalidate your session. As you receive a http 200 from the token extension endpoint your current token must be still valid. Removing the database tables might not work because session data is eventually cached in memory.

**Comment by eikek** [comment]
Hi @madduck sorry for the delay; I wanted to test this out but  haven't got time yet :(. This sounds of course really scary! I don't use OIDC (anymore) myself, but test it before each release with my test setup for two IdPs. Could you perhaps share your setup? What IdP and the config (perhaps the compose file) so I can set it up on my side the same way? Of course, redact any sensible things.

**Comment by eikek** [comment]
Hey, I tried to reproduce, bud sadly can't :/ I tried with authentik 2022.7.1 and 2023.8. I think I'm using the same setup. For the collective mapping I have a user attribute defined and also `lookup:docspell_collective` in my config. Perhaps you could also try with `fixed :TONI` instead of the `lookup:docspell_collective`. Not sure what the difference is here and why it logs in automatically. I suspect there is some unexpected response received.

When you click logout, what should happen is: a request goes to `auth/logout` where the response will instruct the browser to invalidate cookies. It will also remove the account info from browsers local storage. If the cookies are still around and/or the `account` is still in local storage, the client can authenticate with that data. Otherwise, it can't.

**Comment by madduck** [comment]
I managed to fix the logout problem, I had a mistake in the logout URL.

However, the issue with the flood of sessions still exists. As soon as I log in, the service worker goes crazy.

Have you looked at the network debugger during and after login, @eikek?

**Comment by madduck** [comment]
Would it help if I gave you access to the server, @eikek? We haven't gone live yet, so now would be the time.

**Comment by madduck** [comment]
FTR, I just verified that the problem (session flood) exists on Chromium/Linux and a clean Firefox profile on a fresh Windows install.

**Comment by madduck** [comment]
@eikek Can you share your config for Docspell and Authentik? Then I will do a bitwise search for differences to hopefully find the problem.

**Comment by madduck** [comment]
Unfortunately, I have to correct myself: logout does not destroy the session. Here is what happens when I click "logout":

![image](https://github.com/eikek/docspell/assets/195073/106d1d85-b987-4c96-9679-2367209940b8)

It all seems right, and I am taken back to the 

Now, if I visit the DMS URL again, I find myself still logged in.

**Comment by madduck** [comment]
Also, in case it's relevant, the session flooding is independent of OIDC. I shall split the two issues then.

**Comment by madduck** [comment]
Moved to separate issues
