### ISSUE TITLE
[api] upload endpoints must return new item IDs

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2327]
When a file is uploaded, it may end up being converted by the pipeline. If this is the case, the DMS itself is the only instance that knows the SHA256sum of the resulting file. Users trying to assess existence of a file using the `sec/checkfile/<sha256sum>` API will never be able to find the file.

The upload API endpoints should return data about the documents the DMS processed, which the user cannot know: SHA256sum is a candidate, document ID definitely should be returned to the caller on success.

**Update**: Solving #2328 would address this issue as well. However, I still think that the upload endpoints can return the information the upload generated, such as the document ID, and potentially save the user one API call, thus speeding everything up.

**Comment by madduck** [comment]
Thinking about this a bit: When an upload goes through, the new item enters the processing queue. It may well be that the ID is only assigned after successful processing. There is *no* mention of the eventual ID in the logs of the job queue entry after the item has been added. If this is the case, then the item ID would obviously need to be generated upon upload, and passed through the processing queue.

**Comment by eikek** [comment]
You are right in that the upload only stores the file as is into the db. Afterwards a job is submitted which will be picked up eventually. The item id is not known until it is created (it could be skipped due to duplicates or in general, the outcome is not known in advance). But there could be a better response for an upload that includes the job id and a better endpoint to retrieve job details for it. That doesn't exist currently.

Currently, you can be notified for job-done events and get a lot of information from the data in the request. For the processing of an upload, you would receive the item id among other things.

**Comment by madduck** [comment]
Yes, that works. However, when I receive the job-done event, I don't have direct access to the information I had available at the time of the upload, e.g. to add custom metadata, or to replace the uploaded file with a `.url` file into the DMS.

Is there a reason why the eventual item ID cannot be assigned at upload time, before processing? Then it could be returned as part of the API response. And after all, the original attachmentsource is part of the same item ID anyway, no?

**Comment by eikek** [comment]
I think it is a bit error prone to generate it first. For one, it can be easy to "forget" and let the item create a new one anyways. The job can fail or skip processing or whatever, in this case the id is useless. Another reason is that it would be quite some work to thread it through all the layers :). I would prefer it being generated with the new item. I think we can still improve so that scripting is a bit easier. It would still be asynchronous, though.

For example, if the upload api would return the job id (which it should), one can rename the file in question to `<job-id>_original_filename.ext`. Once the job is done, the file can be easily found and renamed/moved whatever. A side effect is that files are marked a being processed by that renaming in the filesystem. Then I think I would be also good with accepting a user supplied "id" to the upload request that can be returned with the job done event as well.

**Comment by madduck** [comment]
@eikek I understand that inserting the new item ID at the start of the pipeline will probably not go as smoothly as wanted, and we will run into errors left and right. However, good test coverage should help us get on top of those quickly. I don't think the design is error-prone per se.

If done right, then the item cannot just create a new ID because it expects to be assigned one by the pipeline, and IDs are only ever assigned in one place.

Also, if a job fails, then the ID is not lost or useless, but can instead probably point back to the error log somehow.

Yes, given the job ID, I can also query the job to get the eventual item ID, but that just requires an additional API call, which we could streamline.

**Comment by eikek** [comment]
I think you would still need to query the job, because without it the item id is not worth much. You don't know when the item will exist or if the job failed etc. A failed job (and it's logs) can be looked up by the job id, not the item id (the job system doesn't know kind of job it processes, it doesn't know item ids etc)
