### ISSUE TITLE
Generated SQL is missing a space

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2367]
Just noticed that there's an SQL failure when uploading a file and trying to update the FTS on PostgreSQL:

```
docspell-joex[103677]: 2023.11.10 15:44:37 [io-comp...] ERROR docspell.ftspsql.DoobieMeta - SQL Failure: ExecFailure(UPDATE ftspsql_search SET lang = ?, folder_id = ?, attach_name = ?, attach_content = ?, item_name = ?, item_notes = ?, fts_config = ?::regconfigWHERE id = ? ,List(German, None, None, None, Some(DB Ticket Weimar), None, german, Ident(item.9xAePRDDpfc-FjnS3gr3LEY-3Tp4KjZvYnZ-BgXMJFwdajj)),443032 nanoseconds,org.postgresql.util.PSQLException: ERROR: syntax error at or near "id" Position: 159)
```

There's a space missing in `… fts_config = ?::regconfigWHERE id = ? …`.

This seems to be generated here: https://github.com/eikek/docspell/blob/master/modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala#L144 and maybe just adding a space before `WHERE` would do the trick.

I am a bit confused though because the same problem exists 4 times in this file:

* https://github.com/eikek/docspell/blob/master/modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala#L136
* https://github.com/eikek/docspell/blob/master/modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala#L155
* https://github.com/eikek/docspell/blob/master/modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala#L156

Happy to create the PR, but I have no idea what's going on as I don't understand Scala.

**Comment by eikek** [comment]
Oh no! thanks for reporting. The problem is coming from the [interpolators](https://tpolecat.github.io/doobie/docs/08-Fragments.html#whitespace-handling) used to generate the final SQL (these are coming from an external library, not really a scala language thing). There is `sql"..."` and `fr"..."` and one or two more. The latter _appends_ a space to the fragment. The first one doesn't add any whitespace. So I think the fix is to replace `sql` with `fr`. To be sure it can be replaced in the whole file.

**Comment by madduck** [comment]
> 37 substitutions on 37 lines

PR forthcoming
