### ISSUE TITLE
Is there a documented process to backup and restore docspell? 

### ISSUE THREAD

**Issue by rpgdev** [eikek/docspell#2485]
The project looks interesting and I want to try it out, been looking at some of the documentation but I'm left wondering: is there a documented process to backup and restore docspell? Seems like the documentation is relying on us knowing how to backup and restore the database backend to begin with plus restoring it via docker/compose etc... which seems like a big assumption to make but maybe I just haven't found the right doc. It's probably very straightforward and I'm asking a dumb question but is the backup/restore process documented anywhere?

**Comment by eikek** [comment]
Hi @rpgdev there is not a lots of detailed documentation for this, because the combinations of how people can run docspell is too large to cover all. Plus, in my opinion at least, when running software like a database it is good to know some basics like backup+restore anyways 😏

If you use the defaults, everything is in postgres and you can backup the whole state by making a standard postgres backup. You can just check their documentation, which is pretty good. There is a step-by-step guide targeting the default docker-compose setup for that here: https://docspell.org/docs/install/docker/#backups

hope that helps a bit

**Comment by rpgdev** [comment]
That's disappointing. It would still be great to have some kind of documented process on how to fit the backup restoration together with the application, I mean, even if restoring the db is straightforward enough the user is still going to be left on its own when it comes to fitting that restored db with docspell.

**Comment by eikek** [comment]
I'm not sure if I understand. What is missing in the guide I linked above? The database backup is all that's needed - what do you mean with "fitting that restored db with docspell"?

**Comment by tenpai-git** [comment]
I might be misunderstanding but I think this is becoming more of a feature request to have a backup process executable in the application frontend itself. 

However, to solve the original issue, I think along with docker compose since the (3) supported databases are PostgreSQL, MariaDB, and H2, it can't hurt to add instructions for backing them up. 

Since PostgreSQL is recommended and the existing documentation already includes how to perform this backup in the docker file, I am happy to add how to perform it on a manual installation since I already had to do this on #2445 to change the encoding format anyway. 

I will make a pull request to add documentation on how to backup and restore on the recommended database manually so the process is documented.

**Comment by eikek** [comment]
There is now another guide how to do backups for postgres (thanks @tenpai-git !). I'm closing this then. But feel always free to create new issues should there be questions/something not clear.
