### ISSUE TITLE
Mail sending failed: Invalid Addresses

### ISSUE THREAD

**Issue by gehrigmobi** [eikek/docspell#2514]
Hi, I'm using the latest docker image, v0.41.0 and encountered an issue with sending mails.
The web interface as well as the API return a "Mail sending failed: Invalid Addresses" error:
```
curl -X 'POST' \
  'http://localhost:7880/api/v1/sec/email/send/[mailaccount]/[redacted]' \
  -H 'accept: application/json' \
  -H 'X-Docspell-Auth: [redacted]' \
  -H 'Content-Type: application/json' \
  -d '{
  "recipients": [
    "user@mail.com"
  ],
  "cc": [
    "user@mail.com"
  ],
  "bcc": [
    "user@mail.com"
  ],
  "subject": "Text",
  "body": "Text",
  "addAllAttachments": true,
  "attachmentIds": [
    "CxuUeRUwPTb-5EuLgzvJJMq-Kt1yuaFq8ef-jxtzJcqfHg3"
  ]
}'
{"success":false,"message":"Mail sending failed: Invalid Addresses"}
```
The log shows the following:
```
comp...] [TRACE] docspell.store.impl.DoobieLogging.run:24 - SQL: SELECT a.attachid, a.itemid, a.filemetaid, a.position, a.created, a.name, m.file_id, m.created, m.mimetype, m.length, m.checksum FROM attachment a  INNER JOIN filemeta m  ON a.filemetaid = m.file_id INNER JOIN item i  ON a.itemid = i.itemid WHERE (a.itemid = ?  AND i.coll_id = ? )  (List(Ident(CxuUeRUwPTb-5EuLgzvJJMq-Kt1yuaFq8ef-jxtzJcqfHg3), CollectiveId(1))) executed in 1691400 nanoseconds
2024.02.25 00:06:13:0001 [io-comp...] [WARN ] jakarta.mail.Session.loadResource - expected resource not found: {0}
2024.02.25 00:06:13:0002 [io-comp...] [TRACE] docspell.store.file.BinnyUtils.trace:58 - Prepare statement: SELECT file_id FROM filechunk WHERE file_id = ? LIMIT ?
2024.02.25 00:06:13:0001 [io-comp...] [TRACE] docspell.store.file.BinnyUtils.trace:58 - Initiating transaction 16
2024.02.25 00:06:13:0002 [io-comp...] [TRACE] docspell.store.file.BinnyUtils.trace:58 - Prepare statement: SELECT chunk_data FROM filechunk WHERE file_id = ? AND chunk_nr = ?
2024.02.25 00:06:13:0003 [io-comp...] [TRACE] docspell.store.file.BinnyUtils.trace:58 - Transaction successful!
```

Mail import from this account works, i assume there is something not working with jakarta mail?
Thank you

**Comment by eikek** [comment]
Hi @gehrigmobi that is strange, unfortunately the logs are not so helpful. The WARN line is very likely not the cause. Are your mail addresses somehow special? If it would be possible for you to share them, that would help. You can also send me a private message (matrix or email)

What setup are you using? docker or something else?

**Comment by eikek** [comment]
Hi @gehrigmobi - I haven't received a message yet (looked at mail and matrix). It is still a bit strange to me. The mail address parser is rather lenient, I'd be very surprised should it reject 4 letter tlds. I need to try to reproduce it on my side. The easiest for me would be if you could share the email (eml file) - but I totally understand if that's not possible. Perhaps you can look at the EML file with some text editor end remove all sensible things (I assume the mail body is not important here). Then you can send it to me via email or matrix. Of course, this always has the potential to remove the problematic piece :) but given the error message it must be some mail address.

Another reason could be entirely unrelated to mail addresses - just came to my mind when writing the previous sentence. The smtp server can reject addresses due to whatever - blacklisting, relay etc - then it probably yields the same error message. So if you think all your addresses are fine, perhaps this is a route to try. It could be that authentication did not work, for example. All wild guesses of course :-)

**Comment by gehrigmobi** [comment]
The issue is solved, it was related to the docker and mailserver configuration.

Here is what I've learned:
- The jakarta.mail.Session.loadResource WARN line is not the cause, this also appears when a mail is sent successfully
- The "Mail sending failed: Invalid Addresses" error originates from a rejection on the mail server side, the server log there says: "Helo command rejected: need fully-qualified hostname;"
- Docspell sends the container ID for the helo command: helo=<93b18822ba73>.

As the mail server (postfix) has some restrictions, i.a. `smtpd_helo_restrictions = reject_non_fqdn_helo_hostname`, mail is rejected.
The solution is to define a hostname in the docker compose file, which is then used in the helo command:
```
services:
  restserver:
    hostname: docspell.example.org
```
