### ISSUE TITLE
Adding file again via Web-Upload creates duplicate

### ISSUE THREAD

**Issue by JaCoB1123** [eikek/docspell#252]
When I upload a file again, that's already been uploaded, docspell happily creates a duplicate document. I think it should check if the file already exists and do nothing in that case.

**Comment by eikek** [comment]
Yes, I agree. This would be consistent with the command line upload. Then there would be now way anymore to create duplicates, if someone would want this. It is currently not done on purpose. My thoughts were: people usually don't use this upload page, because there are many better ways. But as a last resort, this way exists and then there shouldn't as much checks maybe.But otoh it is too easy to create duplicates in this way.

**Comment by JaCoB1123** [comment]
Yes, it would probably be nice to at least warn the user somehow but still have the option to do it on purpose.
I switched to the command line for uploading for now, so it's not a blocker for me.
