### ISSUE TITLE
Unable to see webhooks

### ISSUE THREAD

**Issue by mikedolx** [eikek/docspell#2592]
Hi,

I was playing around with webhooks and set up some notification forwarding.

After some time I realized, that there are no webhooks visible in the docspell-ui. I remember clicking on the save button multiple times. 

Now, when I edit a document/item I get four notifications. I guess, I had set up four webhooks, but can't see any of those.

Any idea, how I can either delete all webhooks, or make them visible again?

I'm running in the latest docspell 0.41.0 on docker-compose.

Any hints appreciated.

**Comment by eikek** [comment]
Hi @mikedolx oh that doesn't look nice. For some reason you have a notification hook without a "channel". I think it would be good to check the table `notification_hook`. there are foreign keys into other tables for a certain channel, like `notification_channel_gotify` etc. The problematic hook has id `FGTzoaUQ1vf-jcMwDLx2hWw-MadYsUVS8on-j4ftUFjRnVm` - perhaps you can see in the db some obvious link problem. It would be interesting how you came to this state.

**Comment by mikedolx** [comment]
Hi @eikek ,

thanks für the reply. It took me some time, to get pgadmin attached to the db, but here i am now. Please find below a screenshot of my `notification_hook` table. You may tell me if something looks odd 😁

![grafik](https://github.com/eikek/docspell/assets/15738117/33cb621b-e8d7-45e9-950a-eba45907e676)

**Comment by eikek** [comment]
I'm sorry, I'd need more tables :) The table you showed is the main one and you can see the first row is the hook that is in a bad state (it's id is mentioned in the exception in the logs). If you don't hang on to it too strongly you can just delete that row. Then the error won't appear anymore.

For the cause, there are other tables connection channels to a hook. So that one hook can use multiple channels to send its messages (gotify, matrix etc). This table is `notification_hook_channel`. It probably doesn't have an entry for the `FGTzoaUQ1vf-…` notification hook (or all `channel_x`columns are null).

The message bombardment is probably caused by too many hooks triggered for the same event. If you like to start from scratch, you can empty the table `notification_hook_channel` and afterwards `notification_hook`.
