### ISSUE TITLE
Broken Syntax Highlighting on Configuration Help 

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#262]
Hi, 
on the following page the syntax highlighting is broken: https://docspell.org/docs/configure/
I think all ' should be replaced by `
Sheers
Eresturo

**Comment by eikek** [comment]
Hmm.. I'm not sure. I updated the site yesterday (I think), because I saw the included default-config files were completely broken. This is now fixed for me. Can it be that you maybe look at a cached site? Or do you see something else? This is how it looks like for me currently (which was broken recently):

![Configuration – Docspell Documentation - Mozilla Firefox_050](https://user-images.githubusercontent.com/701128/93264334-42c49500-f7a7-11ea-9035-49e81be50636.png)

Thanks for reporting these things!

**Comment by eresturo** [comment]
I double checked after clearing the cache:

![image](https://user-images.githubusercontent.com/69030648/93268485-8a4e1f80-f7ad-11ea-83ce-ae9ef4a60251.png)
![image](https://user-images.githubusercontent.com/69030648/93268565-a9e54800-f7ad-11ea-8c1f-bcf72be64e12.png)

**Comment by eikek** [comment]
Ah I see, you mean occurrences like
```
`max-mails'
```
? Right, although inside comments, it breaks the rest of the file. I should find a better "fallback" for the config language (that is not directly supported). Thanks!

**Comment by eikek** [comment]
Fixed with 7dbbe03

![Selection_006](https://user-images.githubusercontent.com/701128/93298186-0e76c600-f7f3-11ea-8f99-89d6d8e2849e.png)
