### ISSUE TITLE
Broken Text-Encoding in Filenames after Upload

### ISSUE THREAD

**Issue by pschichtel** [eikek/docspell#2825]
I noticed this recently, but not sure when exactly this started happening, possibly with the 0.42 update.

Any german Umlaute are affected by this, but I assume this might be a general UTF-8 encoding issue.

Here it is in the upload form before uploading:
![image](https://github.com/user-attachments/assets/f816c409-cfbf-4cb3-bf0f-e190f601c4fc)

Here is the document after uploading without modifying it:
![image](https://github.com/user-attachments/assets/75ae59dd-e202-44ec-b53f-b3091264e619)

I feels like a classic case of interpreting UTF-8 as ASCII/ISO 8859-1 on the byte level.

**Comment by pschichtel** [comment]
![image](https://github.com/user-attachments/assets/c025ab9c-294e-48c3-bf2b-9a538fcb9f2a)

The POST request uploading the file has the broken name already.

**Comment by pschichtel** [comment]
I haven't seen an obvious commit that might have broken this.

**Comment by eikek** [comment]
Oh, that is very strange! I didn't change anything on the client for some time. I'll need to reproduce it here. What browser are you using?

**Comment by pschichtel** [comment]
Here is an example file that reproduces this for me in Firefox and Chromium:  [äöüÄÖÜß.pdf](https://github.com/user-attachments/files/17482694/aouAOUss.pdf)

**Comment by pschichtel** [comment]
![image](https://github.com/user-attachments/assets/0d4c67ff-60d1-4d1e-91a2-88015e53c300)

It's interesting to see Firefox (left) and Chromium (right) display the characters differently.

**Comment by RJS32** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by nekrondev** [comment]
#2842 might be related to this

**Comment by nekrondev** [comment]
So it seems that

- a current web browser like Firefox or Chrome will send an UTF-8 based filename like e.g. "Vertragsübersicht" as ISO-8859-1 encoded string inside the `Content-Disposition` mime multipart header. This will result into a wrong formatted Docspell filename, because `http4s` will decode the UTF-8 formatted string as ISO-8859-1 (that's what RFC 5987 tells, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)

Here is what will happen doing the same wrong conversion using Python:
```python3
>>> bytes("Vertragsübersicht".encode("utf-8")).decode("iso-8859-1")
'VertragsÃ¼bersicht'
```

- Docspells Elm UI needs to force the special `filename*=UTF-8''` attribute inside the `Content-Disposition` header. Not being an Elm programmer myself, but asking our AI for assistance there should be a method for the `Http` package called `Http.filePartWithHeaders` that should allow Elm to provide a dedicated `Content-Disposition` adding the nowadays default UTF-8 encoding for the filename.

For reference AI suggested the following code as an example to provide a dedicated header:

```elm
encodeURIComponent : String -> String
encodeURIComponent str =
    String.join ""
        (List.map encodeChar (String.toList str))


encodeChar : Char -> String
encodeChar char =
    case char of
        'ä' ->
            "%C3%A4"

        _ ->
            String.fromChar char


fileParts : List File -> List (Http.Part msg)
fileParts files =
    List.map (\f -> 
        let
            filename = "ä.txt"
            encodedFilename = encodeURIComponent filename
            contentDisposition = "form-data; name=\"file[]\"; filename*=UTF-8''" ++ encodedFilename
        in
        Http.filePartWithHeaders "file[]" f [ ( "Content-Disposition", contentDisposition ) ]
    ) files
```

So somehow parts of this code example must be integrated to 

https://github.com/eikek/docspell/blob/fc3629e3b7efd3e68bf29c9804bac03dfeaab53a/modules/webapp/src/main/elm/Api.elm#L1075C9-L1076C60

I've currently no Elm/Scala dev environment setup so can't tinker around with the frontend code, but hope it helps to understand the encoding problems.

PS:

![grafik](https://github.com/user-attachments/assets/5fc2d805-d4a0-476b-9d21-f04e574e1b01)
(gibt's [hier](https://www.amazon.de/Trendation-Programmierer-Softwareentwickler-Geschenkidee-Techniker/dp/B0CN9373FR)).

**Comment by pschichtel** [comment]
@nekrondev sounds like a good solution. What I still wonder about: Why did it a become an issue now? Especially since @eikek didn't change anything about the client. It that the http4s version used since right after the the 0.41.0 release contains this PR, which seems to perfectly explain the behavior. https://github.com/http4s/http4s/pull/7419

**Comment by nekrondev** [comment]
Yea, that PR makes sense and the maintainers are right that `filename*=` is forbidden for newer HTML5 RFCs. That's why they convert the UTF-8 encoded `filename=` attribute back to ISO-8859-1 default and allow manual transformation by http4s API methods if a specific conversation is needed. Fixing the ELM web UI by adding `filename*=` won't work, because it's no longer supported by `http4s` framework. The burden it takes will be on Dospells backend to re-encode the ISO8859-1 filename string back to UTF-8. The main problem I see here is that you get no reliable information from the browser which encoding should be used. The legacy `filename*=` provided that information, but the HTML5 RFC mentioned in that https4 PR tells us otherwise that it's forbidden to do so.

The back to UTF-8 encoding I think needs to be fixed [here](https://github.com/eikek/docspell/blob/61d082b82ad84ced3e0500ba57531371d9ecc6c1/modules/restserver/src/main/scala/docspell/restserver/http4s/ContentDisposition.scala#L35) where the multipart filenames are processed.

**Comment by pschichtel** [comment]
The issue that I still see: We don't have any information on what the encoding originally was, right? Would we just blindly reinterpret it as UTF-8 in the hope that things at least don't get worse? The last section of https://datatracker.ietf.org/doc/html/rfc7578#section-4.2 suggest that could be a reasonable approach. It also seems like that's what http4s' filename method defaults to. I'll send a PR.

**Comment by pschichtel** [comment]
@nekrondev @eikek #2853
