### ISSUE TITLE
Can't sign-up / sign-in

### ISSUE THREAD

**Issue by papaloewe** [eikek/docspell#285]
Hi,
I will give docspell a try. It sounds great.
But after Docker Installation I am not able to sign-up.
After fill up the sign-up form and submit, nothing happens.

**Comment by papaloewe** [comment]
I just found the solution, sorry.

**Comment by eikek** [comment]
Hi @papaloewe ,

I'm sorry this will be fixed in the next version (if it is what i suspect): See for reference issue #250 

If you used the docker-compos files unchanged, you need to connect in your browser with `http://localhost:7880`. If you use another url to access the docspell server, you need currently to configure this in the config file `docspell.conf` (right next to the docker-compose file).

**Comment by eikek** [comment]
Ah funny same time :) Glad you could found it

**Comment by eikek** [comment]
I'd close this issue, if it is resolved for you?

**Comment by papaloewe** [comment]
Sure, you can close it.
