### ISSUE TITLE
Fatal error?

### ISSUE THREAD

**Issue by papaloewe** [eikek/docspell#287]
Docspell seems to to be exactly that what I was searching for a while. Thank you.

I see this error when starting:
postgres_db   | 2020-09-26 07:12:41.162 UTC [39] FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0

The next problem the processing queue hangs every time when  "Starting text analysis"

**Comment by eikek** [comment]
Thank you!

I never noticed this postgres error. My logs show also this error, really strange. Docspell works however without any problems here (I'm using postgresql 11.7). Are you using the docker-compose file? Or what version of postgresql are you using? I have to search for this error, no clue what this is currently. I can't image another client trying to connect. Docspell uses the newest jdbc drivers. Maybe it's worth a try to use a newer postgres docker image…?

The problem with hanging text analysis is probably due to an out-of-memory error (it should be visible in the joex logs). The joex component currently needs quite some heap. I [updated the docs](https://docspell.org/docs/install/rpi/#joex) just yesterday, so it was wrongly stated there until then. Try to start with 1.5G heap (using `-J-Xmx1536M` or a similar value). When it starts processing the first file, there are some models loaded in memory that require some heap. Subsequent processing should lower memory usage a bit.

**Comment by papaloewe** [comment]
I am using your original docker configuration via git download.
But where to insert the option -J-Xmx1536M ?
Is it possible as an enviroment statement in the docker-compose.yml?

**Comment by eikek** [comment]
Oh good question. I think you can change it in the `docker-compose.yml` file. There, there is a line `command: /opt/docspell.conf`. Try changing it to:
```
command: -J-Xmx1536M -- /opt/docspell.conf
```

**Comment by papaloewe** [comment]
This 
> command: -J-Xmx1536M -- /opt/docspell.conf
 in the docker-compose.yml is not working:

docspell-joex | # There is insufficient memory for the Java Runtime Environment to continue.
docspell-joex | # Native memory allocation (mmap) failed to map 614465536 bytes for committing reserved memory.
docspell-joex | # An error report file with more information is saved as:
docspell-joex | # //hs_err_pid10.log
docspell-joex | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000a4800000, 614465536, 0) failed; error='Not enough space' (errno=12)
docspell-joex exited with code 1

**Comment by papaloewe** [comment]
Ah, too many Docker Container in my enviroment.
After shutting down some of the other, it seems to work.
Very good.

**Comment by eikek** [comment]
Hi @papaloewe , I'm closing this, it seems resolved? If not, just reopen it or create new ones. Thanks.
