### ISSUE TITLE
Bug: Details are opened even when ctrl-key is hold

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#330]
_when clicked on a document in the overview_

Browser default is that the Link is opened in another window/tab. Actually that also works, but additionally the details are loaded in the current window as well.
Funny thing is, when I select _Open in new tab_ from context menu, this doesn't work at all :-(
So there is no real work around, to work with several tabs

That especially sucks when you have a lot documents, because the back button will not return to the scroll state or better to say to the lazy loaded state, so one has to load the additional documents again and scroll down again...

**Comment by eikek** [comment]
Thanks for reporting, I really never ran into this…

Problem is, the link is opened via javascript. This should be fixable by simply using a `href`.

Then the browser's back button should also restore the previous scroll state.

**Comment by eikek** [comment]
There is an in-app back button that tries to restore the scroll state. But it doesn't work with items that were loaded additionally (clicking "Load more"). The browser's back button will behave the same with the next release. 

Making it restore the additionally loaded state is tricky. I would think the "Load more" button is rarely used; you'd usually just narrow the search before hitting "Load more" often, no? That's why I would leave it, creating a separate issue and see how important it is to others.
