### ISSUE TITLE
FR: Filter on `Scan Mailbox Task` 

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#384]
I think it is really amazing that you can even archive whole e-mails by just forwarding them to the account Docspell scans automatically.

But most of the times, I only want the attachment to be considered and imported.

Maybe you could add two things

1. A filter on filetypes (eml would be the email itself, but sometimes there are also some images I wouldn't want to be added to the item - so I would just choose pdf here).  
2. A filter on subjects (regex?) to have the ability to have certain sets and assign different target folders to different subjects. 

Combining those two features would even make more sense in that one could have certain rules leading to only pdf archiving and others to archive everything Docspell finds in the mail

**Comment by eikek** [comment]
Regarding forwarding: just as info, another possibility (which doesn't require polling or plaintext passwords) is to use a custom "receive-only" smtp server (see [here](https://docspell.org/docs/tools/smtpgateway/) for some details). then you can forward to this mail and it is uploaded immediately.

1. You mean filetypes inside an email, right? So to only import all pdf files?
2. Yes, that should be possible to add.

**Comment by eikek** [comment]
For 1) I create a separate issue #385 . This is not related to mail, but is implemented in the processing steps. So it will be generally available when uploading archive files (zip and eml). After that is there, the scan-mailbox-form needs to be updated, of course.
We can use this issue for enhancing the scan-mailbox-form to filter mails by subject. Wdyt about using globs instead of regexes? I know regexes are much more powerful, but also harder to use. 

Another idea for a filter is to only allow people from your address book.

**Comment by totti4ever** [comment]
> Regarding forwarding: just as info, another possibility (which doesn't require polling or plaintext passwords) is to use a custom "receive-only" smtp server (see [here](https://docspell.org/docs/tools/smtpgateway/) for some details). then you can forward to this mail and it is uploaded immediately.

Wow, crazy story. Think I'm fine with polling :-)
Have you had any issues when polling, when you did it every 5 minutes or even every minute?


> 1. You mean filetypes inside an email, right? So to only import all pdf files?

exactly!


> Wdyt about using globs instead of regexes? I know regexes are much more powerful, but also harder to use.

Personally I would prefer globbing as well!


> Another idea for a filter is to only allow people from your address book.

That is actually a great idea, I would say. I was thinking whether one would have to be able to filter on the from, too.  
BUT when mails are forwarded, they always come from the owner's mail account. Apparently Apple's Mail app add the `References` header which could help, but I think this could be quite prone to errors with too many different clients out there.  
BUT²: I could imagine that together with the subject filter I could just redirect certain mails directly to the docspell server and not just forward them. So it might still be quite useful to have the mails checked against the address book?




> For 1) I create a separate issue #385 . This is not related to mail, but is implemented in the processing steps. So it will be generally available when uploading archive files (zip and eml). After that is there, the scan-mailbox-form needs to be updated, of course.

Ah, didn't know, ZIPs are supported as well, great!

**Comment by eikek** [comment]
> Have you had any issues when polling, when you did it every 5 minutes or even every minute?

I didn't really test it. My import is scheduled every 2h and since I now have a button in my mail-client that uploads it directly from there, I hardly use it anymore. But… it *should* work :). If the polling takes longer, the next job should not be scheduled while a previous one is still running. 


> That is actually a great idea, I would say. I was thinking whether one would have to be able to filter on the from, too.
> BUT when mails are forwarded, they always come from the owner's mail account. Apparently Apple's Mail app add the References header which could help, but I think this could be quite prone to errors with too many different clients out there.
> BUT²: I could imagine that together with the subject filter I could just redirect certain mails directly to the docspell server and not just forward them. So it might still be quite useful to have the mails checked against the address book?

Strangely I really didn't perceive the forward-mail use case back then, although it is so obvious…. My thoughts were that you'd go through your mails (like doing every other day…) and move all that are "important" into a folder that is polled. For similar cases, the from-filter would be still useful, I think: you can poll "INBOX" and apply this filter so not all junk is imported. 

But you're right: when forwarding the mail, this isn't useful anymore. Using the `References` header could help, iirc they contain message-ids. So they can be looked up in the db, but requires that a previous mail was imported. It is error prone as you said! So I think this filter can be useful, but *I* don't have a use for this, so I'd create a separate ticket and see how useful it is to others. If no one cares, I can work on other things :)

Forwarding could also be supported by telling docspell to import (all) attachments only. Then forward the mail as eml-attachment (some mail clients can do this).
