### ISSUE TITLE
Improve mass-edit mode regarding tags

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#412]
Hey, I really like the new mass-edit mode and it helps a lot in setting/removing certain correspondents and concerned persons/equipment, i.e. all those properties which have a 1:n relationship.

From my point of view it more ore less completely lacks value for tags as it replaces already existing tags. This means, if I want to add a tag (e.g. _bill_) and the items had other tags (e.g. _important_) before, the existing tags will be removed and both have only the new tag.

I think/hope there is an easy way around this:
* Just add newly added tags
* For removal certain tags, the way could be to first add the tags to be removed and in the same step immediately remove it again. So removing tags which have been added in the same mass-edit session would be fine/expected for me

But please don't remove all tags just when trying to add a new one.

**Comment by eikek** [comment]
Yes I thought about this and decided to go the easy way first. The reason is that the dropdown field (I created) is completely messed up and needs to be rewritten at some point. I want to avoid adding/changing too much in there. Currently I can only choose what to do with *all* selected tags. That makes it hard to do as described in your second point (which I really like; and I will check out if it is possible). What I can provide is a bit more complex: Another button for changing "modes". The initial is to only add tags. When clicking the mode changes to "removing" and the dropdown is cleared. Selected tags in this mode are removed. A third mode for replacing tags (as it is currently) would be ok then. wdyt?

**Comment by totti4ever** [comment]
That would actually fulfill my personal requirements:
* adding tags, independent on which tags selected documents already have (i.e. don't delete tags when adding)
* removing a single specific tag from a group of selected items, without touching other tags those items may have

Maybe not the prettiest way, but still straight forward and intuitive (also compared to proposal of deletion, which is not really intuitively itself either!)

The third mode might indeed be nice to have (make sure all selected items have exactly the given tags and no others) - but it'd be great if that's not the default mode, indeed!
