### ISSUE TITLE
Consumedir keeps on restarting

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#470]
This seems to be the case since a couple of day(s) - I read something you introduced the check for the consumedir if everything is setup correctly. The thing is, besides a new docker image I didn't change a thing and before it worked :-)

```
Checking integration endpoint: curl  -i -s -o /dev/null -w %{http_code} -H Docspell-Integration:t.........b http://docspell-restserver:7880/api/v1/open/integration/item/_archive
[ERROR] 404 response integration endpoint: curl  -i -s -o /dev/null -w %{http_code} -H Docspell-Integration:t.........b http://docspell-restserver:7880/api/v1/open/integration/item/_archive
```

**Comment by totti4ever** [comment]
Where does that _archive come from? Does it check for the first subfolder in the docs folder? Cause that _archive is the place I copy the successfully uploaded files from within my cleanup script, there is no Collective named `_archive` in Docspell

**Comment by eikek** [comment]
Yes, I tried to add a global check to catch config issues at start. And I simply assumed that all directories are valid collectives; I thought that this would apply to most/all home-users. Maybe too bold :-) That it restarts is due to systemd or some other "process-watcher" that usually can be configured to restart on failure a couple of times.

I think I might just remove this check for now. There are several issues: first these bash scripts are meant to live until I have time to create a better and more complete CLI tool. Then the integration endpoint can be disabled by a collective any time. So it may be ok when uploads don't work. People need to look at the logs. For home-use this shouldn't be a problem, as you probably either don't use it or enable it for all.

**Comment by totti4ever** [comment]
Restarting comes from my compose config, that's right. Quitting come from the consumer.

Actually it might have not been a good idea to place the archive under the consumedir as this also makes consumedir try to handle files moved there (which is denied because there is no Collective with that name, but still not nice)!

**Comment by eikek** [comment]
> Restarting comes from my compose config, that's right. Quitting come from the consumer.

Right.

> Actually it might have not been a good idea to place the archive under the consumedir as this also makes consumedir try to handle files moved there (which is denied because there is no Collective with that name, but still not nice)!

I also think it's better to leave this directory to consumedir. But I'll remove the setup check, because it's not reliable. It currently checks all subdirs. But it may happen that one collective disables this route and then it shouldn't bother other users.

**Comment by totti4ever** [comment]
Would it be that complicated to just have a new API call, independent on collectives? Just like /api/status --> 200 I'm alive plus /api/status/sec or something like that.

**Comment by eikek** [comment]
There is `/api/info/version`. But that's not very useful here I think?

**Comment by eikek** [comment]
In this case it's not related to authentication, too. For a "secured" tests, there are the `/login` or `/session` routes.

**Comment by totti4ever** [comment]
As long as there was a secured call or the existing call would state whether the call was secured. Because that's the thing the consumer dir has to check, doesn't it?

**Comment by eikek** [comment]
The consumedir script uploads to open endpoints. Only the "integration endpoint" is protected by a header value (for example), but this can be switched of dynamically by each collective. So a check here doesn't make sense. The other case, it uploads to "source url", which are protected in that they are hard to guess cryptic urls that only the user knows. But otherwise they are open for uploads.

**Comment by totti4ever** [comment]
I thought something like `/open/integration/status`, which then returns whether the header value is accepted. Because the header value is unique for all Collective's isn't it?

Other option would be to go through all subfolders of the consume dir and check whether it is available (`/open/integration/item/{folder-name}`). Then just write this information as a warning in the log and don't quit. Maybe, because of startup times, try it again after 30s for 3 times if it fails or so...

**Comment by eikek** [comment]
> I thought something like `/open/integration/status`, which then returns whether the header value is accepted. Because the header value is unique for all Collective's isn't it?

Yes, right. This would be an option. A downside is that it is then easy to be "brute-forced" - more a theoretical downside :-)

> Other option would be to go through all subfolders of the consume dir and check whether it is available (`/open/integration/item/{folder-name}`). Then just write this information as a warning in the log and don't quit. Maybe, because of startup times, try it again after 30s for 3 times if it fails or so...

I think this is a good idea. It's iterating through all folders now anyways. A message that a certain folder will not work out is fine. People need to consult/monitor the logs of the consumedir process, since a "restart-on-error" policy is quite common and so quitting doesn't help. The output of curl is also printed in case of error. It turns out that it was prepared for it already, but that `curl -s` suppresses the output.
