### ISSUE TITLE
Dates in ##/##/#### format are only being proposed as MM/DD/YYYY

### ISSUE THREAD

**Issue by bjeanes** [eikek/docspell#561]
I have documents with DD/MM/YYYY (a common format in Australia, but ambiguous due to America's common MM/DD/YYYY).

Presently, on the few documents I've checked, Docspell only appears to suggest a date based on interpreting this string as MM/DD/YYYY.

Ideally, it would propose both. An alternate approach is to make the app locale-aware, _however_ I have lived in the US too and most people have used services based in the US which may use US dates on receipts etc. Either way, I have documents with dates spanning multiple locales, so the safer approach may be to propose all valid interpretations of a timestamp.

**Comment by eikek** [comment]
Thanks for reporting! I didn't know that Australia uses DD/MM/YYYY. This date should be detected but only one is selected and due to the document language being "English", the US format is preferred. I think it should be simple to extend it to choose more than one date for English. It should work, if the US format results in an invalid date, though (like 24/05/2020).

One could extend the document language to a document locale… but I think it is not worth it for this date only? Maybe past documents can be looked at to choose better. Mostly it should only differ in clicking a different proposal.

**Comment by bjeanes** [comment]
>  I didn't know that Australia uses DD/MM/YYYY.

To the best of my knowledge, the US is the only country which does MM/DD/YYYY.

> Mostly it should only differ in clicking a different proposal.

This is definitely what I had in my mind, as it covers the most bases and makes the fewest assumptions.
