### ISSUE TITLE
Scan Mailbox: all items in time range are moved to the target folder

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#576]
Hi, I don't know if it's a bug or if I missunderstood...
I create a Scan Mailbox Task with following configuration: 
- received since hours: 24
- Subject Filter: see your invoice*
- target folder: blabla
This task works, all _relevant_ mails get imported to docspell.
But _ALL_ mails received since 24 hours are moved to the target folder and not only the imported ones.
Is this a bug?

**Comment by eikek** [comment]
Hi @vakilando ,

currently, this is intended, but I'm not super happy with it. I changed it recently, it is related to #551 .

The reason is that when the task performs again, it should not see mails from previous run again to not "starve". But this seems to me only a problem when importing a lot of mails at once. The initial use-case of this task was to periodically import some mails. Hm, not sure what to do with it.

**Comment by vakilando** [comment]
ok, I see what you mean.....
I'm using the filter "Received Since Hours" (set to 24) and the scheduling. 
That way the task will not see the mails again from previous run when it performs again.
Perhaps there should be a separate option for a "first bulk import"?

**Comment by eikek** [comment]
Yes right, you are using it like it should be used :-) These two use-cases are different. I think about reverting the change from #551  and provide a separate (and hopefully better:)) bulk import in #557 . 

For a first rough version, maybe a flag in the config can be used to distinguish between applying the move/deletion before or after the filter. This is not user friendly and applies to all collectives… but it might suffice for a while.

**Comment by eikek** [comment]
I'm now adding yet another flag to the scan-mailbox settings to decide which way to take for post processing. This is not super nice, but it is now correct at least. Hope to find a more ux-friendly way with #557 .
