### ISSUE TITLE
Mail import: Mail format issue

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#591]
I have exported old mails from thunderbird with the "_save as_" function as **.eml** files in a folder.
Most of them were properly imorted by docspell but some of them were not or wrong imported (empty pdf attached).
I figured out that they had a "special format"

This is a part of such a mailfile.eml: 
`Ihre Rechnung ist im PDF-Format erstellt worden. Mit Klick auf den Anhang w=`
`ird Ihre Rechnung automatisch mit einem installierten PDF-Reader, z. B. dem=`
` Adobe Acrobat Reader ab Version 8.x, ge=F6ffnet. Sollten Sie keinen Acroba=`
` t Reader installiert haben, finden Sie hier den Link zum kostenlosen Downlo=`
` ad: http://get.adobe.com/de/reader/
`

As you can see there is a problem with 

1. german umlauts: "**=F6**" is ment to be "**ö**"
2. line break

After replacing all the german umlauts and deleting those line breaks (=) the import worked flawlessly.

My questions: 
Is there a thing you can do? 
Do others have the same problems?
Or is it a specific thunderbird (on linux) problem (I have)?

[EDIT]
just tested and teedy has no problem importing those mails. But the mail text is not converted to pdf it's imported as text in a text field (like the "_notes_" in docspell).

**Comment by eikek** [comment]
Hi @vakilando , thanks for reporting!

This text looks actually ok. It is encoded using whats called the `quoted-printable` encoding and is very often used in mails. The =F6 are hex codes for byte 246 which is the character `ö` in the latin1 character set. Docspell should read these texts without problems, I tested these kind of content a lot. So I suspect that the mail advertises a wrong mimetype/wrong encoding somewhere. When it worked after you removed all this, it might be missing a `Content-Transfer-Encoding` header (or one that is not quoted-printable). 

Did the attachment of that mail arrive correctly in docspell?

I could best analyze it if I could have the complete eml file. But of course, these are sensible documents. Maybe it is an option to send me this eml file (you can do so via email) without the content, but leaving the structure and headers. So for example, remove all lines that contain sensible information. The Base64 lines of the attachment(s) can be removed completely (you can leave the first line maybe). If that is not possible, could you send me the main headers – all lines until the first empty line? If you remove a header, please leave the header name in place and replace its value (like `Subject: <redacted by me>` or something). It is good when the structure doesn't change. If this is possible, you could send it (as attachment) to `eikek [at] posteo.de`. If you need help, we can chat privately via mail or gitter, too.

Others may have the same problem. E-mail as a protocol is simple, but the content is easy to get wrong and there are many mail clients (sender) out there that don't comply to the specs (well, RFCs). Mail clients (reader) often have quite some code to circumvent these things, because people want to see their mails obviously. So it depends in part on which programs the sender uses. But, of course, it might be a completely correct mail and the bug is in docspell….

It may also be a problem in thunderbird, as this is the tool that creates the eml file. But I think it's not very likely.

**Comment by vakilando** [comment]
> Did the attachment of that mail arrive correctly in docspell?
- without editing .eml: No, nothing arrived.
- after editing .eml: yes.

This is how it looks when importing the file (without editing):
![1_import-stuck](https://user-images.githubusercontent.com/36138919/105627713-cd459100-5e38-11eb-85f2-590660bc7530.png)
![2_import-stuck-log](https://user-images.githubusercontent.com/36138919/105627714-ce76be00-5e38-11eb-87e7-8846710fbb32.png)
![3_import-failed](https://user-images.githubusercontent.com/36138919/105627716-ce76be00-5e38-11eb-8dd2-a832444baf83.png)
![4_import-result-overview](https://user-images.githubusercontent.com/36138919/105627717-cf0f5480-5e38-11eb-860e-540a9399a490.png)
PDF viewer: viewerJS
![5_import-result-detail_viewerJS](https://user-images.githubusercontent.com/36138919/105627718-cf0f5480-5e38-11eb-8da8-b271647fc9c3.png)
PDF viewer: Native
![5_import-result-detail_Viewer-native](https://user-images.githubusercontent.com/36138919/105627719-cfa7eb00-5e38-11eb-8fd3-4933004efd96.png)

I'll see if I can send the whole .eml to eikek [at] posteo.de

**Comment by eikek** [comment]
> > Did the attachment of that mail arrive correctly in docspell?
> 
>     * without editing .eml: No, nothing arrived.
> 
>     * after editing .eml: yes.

Oh, that is really strange.



> I'll see if I can send the whole .eml to eikek [at] posteo.de

Thank you that would make it much easier for me to analyze. However, I totally understand if you don't feel like doing this.

**Comment by vakilando** [comment]
you have mail :-)

**Comment by eikek** [comment]
After a quick look, the mail is totally fine. So I'm now searching for the cause. The mail library in use complains that there is no input…. I'm wondering what it is, reporting back when I know more.

**Comment by eikek** [comment]
Ok, found it. The problem is that the mail body (the "text" part) is encoded using the iso-8859-1 character set, but it doesn't declare it. The content type is only `Content-Type: text/plain`. The [standard says](https://tools.ietf.org/html/rfc2045#section-5.2), it should interpreted as us-ascii. 

The mail library is trying to decode it using utf8 (because I found many mails to be using this), which includes the us-ascii charset – so it can also decode us-ascii text just fine. And this fails for the "special" bytes in the iso-8859-1 set (like `ö` etc). By changing the text yourself, you probably changed it to be plain-utf8 encoded bytes, which is why it was working then.

If you change the content type header to this:  `Content-Type: text/plain; charset=iso-8859-1` then it will be imported correctly.

So… I think in case the mail doesn't advertise its encoding, I'll simply go through a few known ones, first utf8, then iso8859 etc. This is again yet another workaround for incorrectly formatted mails :-).

**Comment by vakilando** [comment]
> Ok, found it

Wow, cool! Thank you for your fast response and solution!
