### ISSUE TITLE
Tag or Concerned equipment?

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#598]
Good Morning,
first of all: super cool new release. Finally automatic tagging :memo: :smile: 

My question today is question about a usage recommendation. Should I prefer to use tags or concerned equipment? As an example: I have different insurances and now I could do the following:
1. all items get **tag** _insurance_ (no category) and **concerned equipment** _insurance name_.
2. all items get **category tag** _insurance_ and as **tag** _insurance name_.
3. something else?

What advantages / disadvantages do I have with each option? In my old document management system I used tags for everything (correspondent, concerned, equipment, ...) , so I still find it hard to get rid of them.

Sheers
Eresturo

**Comment by eikek** [comment]
Hi!
That's a good question! Tbh, I don't know :-) I guess whatever works best for you is great. So if you don't need equipments, disable the field and it's out of the way. I think you shouldn't feel like "getting rid of some tags" – if you it works, that is great, no?

I can share some thoughts that lead to the existence of the concerned part and how I use it. But this might be just a bad way in general and/or for others :-). TL;DR I think both variants are fine. I would personally prefer 2. Another variant could be to track insurances as correspondents. I think it depends on how you need to find the docs again and what information is important for you to track.

Since I'm a lazy person and documents arrive quite often here, I don't want to think about "where to put it" each time. So instead, the basic idea was to only attach information that emerges from the document itself (content, mostly). That is easy and can be done automatically quite well. But it also optimizes the "stow away" part, which is great for me, since I'm fine to spend a minute when searching for something. So now I'm scanning almost everything, import mails and then quickly go through all new documents every week to fix metadata.

My previous "DMS" was an org file in my Emacs, that I organized around corresponents. I found out that I use the correspondent and a rough date most of the time (by large) when looking for a document. Then, sometimes, I had the need to distinguish documents further. For example, we have medical reports that apply to me or to my child. Or for a company, I can imagine documents to insurances and government departments that apply to a customer/employee etc. And sometimes it applies to some "thing" – the equipment (didn't find a better word). I also used tags for this in the past. But I figured that some may be worth to track separately. For example, I also wanted to track contact information for companies and people, so I can get back to them when I'm "working on" some document. This is the main reason for concerned equipments/person. And it appears to me a "natural" way to organize this in an address book. After all, if you don't care about that, everything could be a tag.

I myself use equipment for all "larger" things that I expect documents to arrive for and that I like to track by itself. For example our flat, the car and some digital products; entities that have a meaning in itself. Everything that represents "someone", like companies (insurances) and people, I use the correspondent for (when I receive or send documents from/to them).

In your case it sounds like I would maintain all insurances as companies in the address book and track them on the correspondent field…. Not sure, of course, if that makes sense in your case.

But… it thought more than once about removing the equipment, because right now it is really only a tag. Only difference is, that it is used for suggestions. OTOH I would like to extend it a bit. I'd like to have a description field where I can put serial numbers etc for some devices… and then I think this may well go too far :). I think it's nice to have it, but also that you can simply hide it and don't use it at all.

**Comment by eikek** [comment]
Hi there! If you don't mind, I'm closing this. Just reopen if something is missing!
