### ISSUE TITLE
SQL UNIX socket connect?

### ISSUE THREAD

**Issue by eisengrau** [eikek/docspell#622]
Hello,

I am currently running a MySQL (MariaDB) instance on a different host, with a socket path exposed on a shared storage. I would like to install Docspell on another container, however I do not wish to add a new SQL instance there as well. Is it possible to configure docspell server anf joex to connect to an unix socket for the My or Pg SQL database, instead of a TCP port?

I can imagine something like providing url = "jdbc:postgresql:///path/to/pgsqldb.sock instead of url = "jdbc:postgresql://localhost:5432/docspelldb"

Thank You,

**Comment by eikek** [comment]
Hi! that's a good question, I never had the need for this, so I don't really know. I don't think this is possible. I'm not even sure, if java can handle unix sockets at all (there are libraries for sure, I mean in the standard sdk). Is this working well for other projects? I'm wondering how mounting works, so both containers need to be on the same machine, right? Otherwise there is some network in between, if it's working at all (never tried that). But it's an interesting idea; I can imagine that this is a nice way to have "your own db" attached to a app container….

From a quick search, I didn't find any results regarding mariadb and jdbc + unix-socket. I found something regarding postgres, though. I'm afraid I can't help you here.

Why can't you use a tcp socket – is it only for the performance gain?

**Comment by eikek** [comment]
Ah, just found this https://openjdk.java.net/jeps/380 seems that java will be able to support unix sockets in the future. I'd say this currently not possible. :-/

**Comment by eikek** [comment]
Hi @eisengrau did you maybe found out anything regarding the use of unix sockets? If I can help with anything, let me know. If you are fine, I would close this then?

**Comment by eikek** [comment]
Closing this now. Feel free to reopen or use new issues any time.
