### ISSUE TITLE
Setting up with mysql issue

### ISSUE THREAD

**Issue by eisengrau** [eikek/docspell#623]
Hello,

I have followed the guide to specify a Mysql server in both restserver and joex config files, I added a similar line to both configs, of course commenting out the H2 database string:

 jdbc:mariadb://172.0.0.124:3306/docspell

When I restart the docspell-restserver, it all startup up OK, it populates the db schemas in the then empty db and the rest gui is accessible.
However when i restart docspell-joex, it will fails to launch, in the logs complaining about some tables in the db already present, apparantly it tries to add the same schemas as previously but fails.

Did I miss something in the config step? Do restserver and joex should have their all seprated DBs?

**Comment by eikek** [comment]
> However when i restart docspell-joex, it will fails to launch, in the logs complaining about some tables in the db already present, apparantly it tries to add the same schemas as previously but fails.

This is very strange, I cannot reproduce it with my MariaDB (10.4.15). When migrating, the states are memorized in the table `flyway_schema_history`. It only applies changes not listed there. So what you describe should not happen. Can you show some logs? 

Does this happen when starting out with a new (empty) database?

> Do restserver and joex should have their all seprated DBs?

No, they require to have a connection to the same database. I can't see that you are doing anything wrong. It should work, joex and restserver must both have the same jdbc url.

**Comment by eikek** [comment]
Hi @eisengrau , just getting back to ask whether I can help in any way? Did you maybe resolve this?

**Comment by eisengrau** [comment]
Hello,

Yes, I'm so sorry I wasn't able to reply earlier.

So, the issue still stands. Basically, the issue is the other way around: when starting up with a new empty database, all is good, schema is imported. I could start with either joex or restserver. However when I try to start up the other component, it tries to import the same schemas and fails.

I can attach you some logs here, or try doing those fancy terminal-to-gif aimations as well.

This is more important than my other #622 issue.
Thank you.

**Comment by eikek** [comment]
Hi, 
no need to be sorry! I just occasionally look at older issues :) Should I close one due to inactivity or something, just reopen it or create a new issue!

I think I need some logs to look into it, because I can't reproduce it. I think it would also help to rule out any environmental things, just to be sure. Would it be possible to just run the provided zip files? (instead of using docker, if that is used for example). What version of mariadb are you using? We can then also try with, for example h2, to see if it can be reproduced there as well – if you unpack both zip files and run one then the other it will default to a h2 database. If that already doesn't work, it's probably not even db related. Should it work, we can look running it against mariadb. I'll try it myself with the zip files only later today.

**Comment by eikek** [comment]
Hi, I'm closing it now due to inactivity :-) but no worries, just reopen it if you have more information or create new issues.
