### ISSUE TITLE
remedial questions regarding hardware requirements

### ISSUE THREAD

**Issue by CouldBeThis** [eikek/docspell#669]
Hi, 

So after writing all this it occurs to me that maybe the reason I am so confused is because I am very far from having the technical skills required to run this project. If that's the case it's fine. :) There's lots of other stuff I can do. But I am going to submit it anyway by way of feedback, and also in case the complexity is not actually as great as it appears. But please no one feel obliged to spend a great deal of time explaining all of computer science to me. 

---

I am thinking of installing this but my most available place to put it is a [RBP3B+](https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/) (1 gb RAM). I see on the [relevant docs](https://docspell.org/docs/install/rpi/), it says 

>  The board should provide 4G of RAM (like the current RPi4), especially if also a database and solr are running next to it.

So I can comprehend the first part of that sentence but not sure about the meaning of the second half. Also looked through [memory usage](https://docspell.org/docs/configure/#memory-usage) and [text analysis](https://docspell.org/docs/joex/file-processing/#text-analysis) docs. Only vaguely understood parts of that and not confident of those. Lots of words in there I have never even come across before.

Assuming I had the requisite hardware, do I *need* to be able to understand all that stuff to run this?  Optimistic speculation suggests all the technical detail is included for the joy of it. (It's quite endearing how much care has gone into this even though it's over my head.) Does it come with a reasonable default configuration? 

I really appreciate it when open source projects are clear about the cognitive requirements to run/manage as well as the system resources. That way I can plan what to run in a way that will complement my learning. I think there is sometimes a bit too much focus on being (appearing) "easy". If it's not, it's not.

**➡️ This is the main part of the question:** Regarding my 1GB situation, which of the following applies?: 

1. Probably wouldn't be able to install it
2. It would install but there would be a lot of problems and it wouldn't necessarily be stable
3. It would run, it just wouldn't run very fast
4. It would run, but missing some features

If I understood properly, the docs suggested that running at lower RAM might be possible if regex was used instead of NLP.  What does that mean? Maybe if ever you were looking to make the docs a bit more understandable it would be helpful to show or describe an example about a use case with one vs the other. Maybe I don't need NLP?

Also when I was trying to understand the docs, I was *sort of* getting the impression a lot of the work is done as a one off. Like I *think* the software does the NLP magic and then puts it in a database (or something). Specifically:

> Training the classifier is also memory intensive, which solely depends on the size and number of documents that are being trained. However, training the classifier is done periodically and can happen maybe every two weeks. When classifying new documents, memory requirements are lower, since the model already exists. [source: [memory useage](https://docspell.org/docs/configure/#memory-usage)]

and

> Training the model is a rather resource intensive process. How much memory is needed, depends on the number of documents to learn from and the size of text to consider. Both can be limited in the config file. The default values might require a heap of 1.4G if you have many and large documents. The maximum text length is set to 5000 characters. If *all* your documents would be that large, adjusting these values might be necessary. A model is trained periodically, the schedule can be defined in your collective settings. Although learning is resource intensive, using an existing model is quite cheap and fast. [source: [classificaiton](https://docspell.org/docs/joex/file-processing/#classification)]

It gave me an idea: Would it be possible to primarily run off the low-resource RBPi, but occasionally use a higher-spec machine to run more complex tasks, which could then be accessed later? For example could I unplug the external hard drive from my RBPi, plug it into my desktop (which has more RAM obvs), leave it to do a bunch of work, then return it to the home device?

For my purposes "possible" means that it would work with zero/minimum fiddling around. 

Also if it could do everything itself, just very slowly, that would be fine too. I don't mind if it take a day or two to nibble away at a batch of documents. I am in no rush. But if it would be crashing, stopping, needing a lot of back-rubs and tea, then it would be less tenable. 

Looks like a great application and thanks for sharing your evening project. :)

**Comment by eikek** [comment]
Hi @CouldBeThis , thank you very much for your feedback! At first, I want to apologize for these technical terms used in the docs. I never meant to scare anyone away, so I'm very glad you took the time to write all this!

Then, for all reading this, if something is not clear, don't hesitate to ask here or in matrix/gitter. I'll try my best to explain or recommend a setup given your constraints of hardware/software etc.

I guess the explanation to all this is that no-one reviews what I do:). So I try the best I can to explain, but once in the writing I sometimes forget the target audience, or covertly change it :). These more detailed explanations do assume some previous knowledge/experience. This project is not in the shape to provide a on-off experience for everyone. This is a lot of work and I mostly choose to code :-/.

The reason is that docspell is very flexible. There are a lot of different scenarios possible, and I was trying to explain how it works generally so that people can adjust to their situations.

To your questions: There is a sensible default configuration that currently opts for activating *all* features. That also means that it is configured for a RBP4 with 4G RAM minimum. That's the current default, so the RPB3 with 1G will not work. If you'd have better hardware the default (docker) setup will "just work".

In your situation having only one single RPB3 with 1G RAM, there are still possible ways by dropping some features. First it wouldn't run *very* fast (this is always highly subjective, in my opinion it runs very well for the given hardware). Now I'm going over many details, the gist of it is always: when wanting more (stability, speed) it costs more in terms of RAM/CPU.

Maybe some basics: docspell has two components - one is showing the website to you. The other is doing resource intensive tasks, like processing your files. The first runs very lightweight. The latter is the one that can use a lot of resources. So you're right with that many things are "one-off". The processing happens once for a file and after that all info is in the database.

You can configure docspell (I can help you here) to remove following features:

- Fulltext search. This is currently based on a separate tool that I would not install on this pi additionally. Docspell can be configured to know that and removes UI elements etc. In my opinion fulltext search is very neat, but quite overstated. In my years of dealing with documents a hardly ever use it. But this, of course, highly depends on your use case.
- No NLP. This removes the suggestions for new documents. Or we can try whether `regex` mode would work. Without any NLP, there will be just one proposal, but not many to choose from.
- Should you have many many (thousands) documents we might need to disable all these suggestions/automagic features. Then you need to add correspondents etc manually.
- You need an external drive for the Pi, the flash card only is not a good medium for this (I think you already have one?).

You can switch these features on later, should you get a more powerful machine.

You mentioned already another way by utilizing your desktop computer, which has more power: We can install the lightweight component showing the website on the RPI3. This way you have always access to your data. You can also upload files, but they *will not be processed*. But since you have a desktop that you switch on occasionally, we can install the second component there. It only needs to know the RPI machine. Then when starting up the desktop, it can begin processing all the files that have been uploaded so far. It also gets notified should you upload files when it is running. The downside here is, that you need to install on two machines and this requires to know the IP addresses/host names etc in your network…. So it's not very easy and can fail in more ways; it requires some knowledge and some could consider this as "fiddling":-). Unplugging the hard-drive is not necessary (and not recommended), if you can "reach" the pi from your desktop.

As a fazit: I'd say to install everything without NLP on the pi and see how well it goes. The classifier can be configured to run only on a few documents. So you have at least some help with adding metadata.

I hope I could clarify a little. Thanks again for your feedback!

Thinking about what tasks to take away from this: I think an important one is to add a TL;DR somewhere that gives some example scenarios where people could identify with one or the other. Maybe it would be nice to provide two config files, one for "light" and one for "all"?

**Comment by eikek** [comment]
Closing this now. Feel free to re-open or use new issues any time.
