### ISSUE TITLE
all Item previews are blurred

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#682]
I think this was not a problem in v0.19. but I'm not sure...
In version 0.20.0 all item preview (imported before and after the update) are blurred.
See the picture,
![docspell-preview](https://user-images.githubusercontent.com/36138919/110181085-545c3080-7e0b-11eb-9748-0e64b7538b81.png)
 
do I have to use the regenerate-previews.sh script?

**Comment by eikek** [comment]
Oh this is quite strange. The files before the update are not touched again. Is this the detail view? Or the little "thumbnails" in the list view?

**Comment by vakilando** [comment]
All the preview are blurred (small, Medium, large).
I use the medium size and didn't change the config. 
The detail pages are fine.

**Comment by eikek** [comment]
I'm sorry, I can't explain this. I can't really see how this is possible. But since it is, there is some bug somewhere. When joex is started, it submits a task to generate previews for all files *where a preview is missing*. I just checked the code and it looks fine. That was something that came to my mind, but I can't see anything wrong here.

There is a little "trick" to check the system jobs. System background jobs are executed as id `docspell-system`. You can register such a collective/user and login to look at the processing queue. Maybe you can see something interesting there.

To move forward, I'd suggest to regenerate all previews again. You can use this shell script you mentioned, it should work by giving it the base url to docspell (it asks for user and password). This will replace all previews. You can also set `docspell.joex.extraction.preview.dpi` to some higher value to create better quality previews (but also larger).

**Comment by vakilando** [comment]
regenerating previews works partially... The process get's stuck. I tried it 3 times.
I'm getting this error:

`2021-03-07T1:10:24: Generating preview image for attachment Ident(GfT1L5v3een-iy9p1uJodfP-7CbBkTGFQ38-La31NRrbfMp)  `
`2021-03-07T1:10:24: Job HrLA3fNvj.../FB/make-preview/Low execution failed. Retrying later.: Page tree root must be a dictionary`    
`2021-03-07T1:13:42: Generating preview image for attachment Ident(GfT1L5v3een-iy9p1uJodfP-7CbBkTGFQ38-La31NRrbfMp) `   
`2021-03-07T1:13:42: Job HrLA3fNvj.../FB/make-preview/Low execution failed. Retrying later.: Page tree root must be a dictionary`

How can I find these attachments by the ID given?

**Comment by eikek** [comment]
You can use the id with this url path: `/api/v1/sec/attachment/[attachment-id]` (it is the url when you click the "eye icon").

The setting for the dpi is in the joex config file. You can find it in the default config for joex [here](https://docspell.org/docs/configure/#joex).

The problem seems to be a pdf that can not be read due to some dictionary problems (it seems related to [this](https://issues.apache.org/jira/browse/PDFBOX-4915) but docspell is already using a newer version of that library). I think to further look into it, I would need the file … should it not be confidential, you could send it to me and I can take a look (thanks!). In case it is possible, I'd be interested in the "original file" (menu at the attachment let's you download it).

**Comment by vakilando** [comment]
hmmm, quit strange... These files are named mail.converted.pdf (ok) and both 24 bytes small. 
They are simple text files with following content: `"Authentication failed."`
How can I find them in the webui?

**Comment by eikek** [comment]
This is really strange! This string looks like the string docspell prints out when a request failed to authenticate. I can't explain how this would end up as a file in docspell.

Finding the item to a given attachment is a bit involved (working on it just now… will be better in next release). There are two options coming to mind:

1. download the file and create a sha256 (linux its `sha256sum` command). Then you can find all items that have files with this checksum:
   ```
   GET http://localhost:7880/api/v1/open/checkfile/{source-id}/{sha256}
   ```
   Use any source-id to authenticate. You need to paste the ids into the browser…
2. Use the database…. The select statement would be:
   ``` sql
   select i.itemid from item i inner join attachment a on i.itemid = a.itemid where a.attachid = '{the-id}';
   ```
   Then again pasting the resulting ids into the browser url (go to some item detail and replace the id in the url).

If the file is really nothing more than this, you could send it to me so I can take a look why it fails the preview (even though a strange file, should not stop it being previewed…).

**Comment by vakilando** [comment]
It seems that I indeed had an expired login in docspell :-|
I did a `Select itemid from attachment where attachid like '%GfT1L5v3een-iy9p1uJodfP-7CbBkTGFQ38-La31NRrbfMp%'`
then a `Select * from item where itemid like '%result-from-above%'`
With the name and the date I searched in docspell and I believe I found the document. It consists of two files (a converted mail.eml and the attached invoice) the converted mail.eml is corrupt...
See picture:
![docspell-temp](https://user-images.githubusercontent.com/36138919/110259701-670c6c00-7fa9-11eb-8e7c-dc23dbbf5b13.png)
I' deleted this file and the regeneration processes are ok!
But... previews still blurred.

**Comment by eikek** [comment]
Can you open only the preview image in a separate tab and check its size? I would now try to raise the dpi setting a bit and then regenerate again. My previews didn't change, but they are blurred if zoomed a bit, so when using preview=large, that would make sense to me.

The corrupt pdf may be a result of a failed conversion. You can download the archive file of that item – this is the original email. You could try (with a different collective or skip-existing-files=false) to upload it again and see if this produces a corrupt pdf again.

**Comment by vakilando** [comment]
The size before raising dpi and regenerating previews:
![docspell-temp](https://user-images.githubusercontent.com/36138919/110321360-dcac2280-8011-11eb-97b3-3aab20eb4ad1.png)

The size after raising dpi (32?>48) and regenerating previews:
![docspell-temp1](https://user-images.githubusercontent.com/36138919/110323746-5265bd80-8015-11eb-9ae9-bb0d9cf7d50b.png)

The size after raising dpi (48>64) and regenerating previews:
![docspell-temp3](https://user-images.githubusercontent.com/36138919/110324554-6e1d9380-8016-11eb-8906-3165b88d19a3.png)

With dpi=64 it's ok and almost readable.
They all Quirks-(compability)-mode, but this seems not to be the reason as other sites also do this (while the graphics are clear).

**Comment by eikek** [comment]
Ah thanks! I think then it works as intended; maybe it would make sense to increase the default dpi size. The default is 32 which results for A4 in roughly a 200x300px image. But I then have to double-check that too large images do not result in an out-of-memory. I think the "blurrynees" comes from the small size of the png that gets zoomed by the browser. It also depends on the source, of course. I'm using the 32dpi setting – it's enough for me for a quick look (I see the logo and the outline of the document, but can't read the text).

**Comment by vakilando** [comment]
I think the default dpi size of 32 is good enough for most people...
I'll stay with 64 or go back to 48, this seems also to be enough for me.
Closing this now as I learned how to change the dpi ;-) !
