### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#683]
Is there a way to tranlate the project? Are "language files" existant? Can we help?

**Comment by eikek** [comment]
Thank you for asking. It might be not really feasible currently; unless willing to code in Elm. There are no language files, I have to do some grunt work first to externalize all the strings. 

I could provide a starting point that can be followed when programming Elm is acceptable, but mind you it's a tedious task :-). It gets a easier once strings are all externalized. It's a bit sad, because I know that it's stupid and much more work to not prepare for that, but happened again 🤦🏼  On the other hand I didn't want to start this until the new ui is there. Now it is, so it can be worked on.

There is #292 for reference.

**Comment by vakilando** [comment]
Don't worry, it's not urgent but would be nice to have it as an option. I can easily wait. You can close this issue if you want.
Whenever you are ready, I would like to help with translation

**Comment by eikek** [comment]
Hi @vakilando , because you asked :) I now externalized all the strings in separate files (hopefully all…). If you like to try to translate the UI, this would be possible now. I wrote something down for [getting started](https://docspell.org/docs/dev/translation/), I hope that's descriptive enough… if not it can be improved.

**Comment by eikek** [comment]
I've added e German translation now. (And found some small bugs along the way). Unfortunately, these are all the natural languages I know :-) so for other languages we need support. I'm closing this now, please file new tickets for spelling/grammar errors or strange wording.
