### ISSUE TITLE
the result of "content search" is not in the right order (by date)

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#686]
When searching using the "_content search_" (full text search) the results are not in the right order (by date).
When searching "_by names_" the results are in the right order (by date). 
When searching by clicking on the tag the result is also in the right oder (by date). 
Bug?

**Comment by eikek** [comment]
This is currently a feature 😄 There is only a sentence about it [here](https://docspell.org/docs/webapp/finding/#contents-only), which is a bit hard to find.

The reason is that there is quite some amount of rocket science inside fulltext components like SOLR (and the underlying search engine Lucene) to give a order that reflects the relevance wrt the search term. That's why the results are simply returned as they are fetched from SOLR.

If adding some other metadata to the mix, I decided to use the "standard" order, as these are queried at the sql database and then the relevance-ordering only reflects the fulltext-search query but not the combination of both.

**Comment by vakilando** [comment]
Ok, "If no other fields are selected, the results are not ordered by item date, but by relevance with respect to the search term."
if one knows that (rtfm) it's even a nice Feature!
