### ISSUE TITLE
Fresh install using Docker => Login failed

### ISSUE THREAD

**Issue by Cruguah** [eikek/docspell#813]
After a fresh install using the installation guide from https://docspell.org/docs/install/installing/, (docker-compose), I have multiple running containers (solr, db, joex, restserver and consumerdir)
The website (localhost:7880) response and I can create an account.
After I created an account I can't login.

What did I do wrong?

thnx

**Comment by Cruguah** [comment]
The problem is solve, The login box was not clear about the username you need to supplier

**Comment by eikek** [comment]
hi @Cruguah sorry for this issue. Glad you could figure it out. Do you think a different placeholder or another sentence in the docs (or at some other place?) could clear this up a bit more? Or anything else that could be improved here?

**Comment by Cruguah** [comment]
Step 4:
Goto http://localhost:7880, signup and login. When signing up, you can choose the same name for collective and user. Then login with this name and the password

What name do you expect when you read: Then login with this **name**. It gives a feeling you don't need to specify the collective but I needed to specify both.
In my humlbe opinion it should state something like: Then login with the collective, username and password. At the login screen the Username field expects the following format: {collective}/{username}

And there is a small bug: When you login without the collective (only username) and the rigth password, you get the user icon in the right top of you're screen and you can actualy open the menu and select for example the Collective Profile. No information is displayed, but still the icon appears while the user is not login.....

**Comment by eikek** [comment]
Thank you a lot, @Cruguah appreciate it! If username and collective name are the same, then you don't need to specify both. That's what I tried to get across with this sentence: choose the same name for collective and user and then login with *this* name (you have chosen) … hm. The idea was to not bother first-time users with too much information :-). I think I rather use your suggestion and maybe add this: "If collective and username are the same, then you can omit the `{collective}/` part."  wdyt? Or maybe just say "Choose the same name for collective and user for now" instead of "can choose" which sounds optional ….

Regarding this bug: I can't reproduce it; whenever I omit the collective, login doesn't work. If collective and username are the  same, then it works as expected here. If I enter a deep link, then I get redirected to the login screen. If you have more info on how you got into this situation, I'd like to hear to be able to fix it. Thanks!

**Comment by Cruguah** [comment]
You're right, can choose makes it confusing.

About the bug, as you can see it's easaly to reproduce, using Chrome or Edge:
![image](https://user-images.githubusercontent.com/14362766/118724432-e54d8000-b82e-11eb-9ddb-bbff2c5f7d1a.png)

**Comment by eikek** [comment]
Aaah yes, now I got it. Sorry, I was too blind! Thank you. The user is not logged in, but the ui thinks otherwise…. This works with any false login. Thanks again, will create a new issue for this.
