### ISSUE TITLE
Show a QR code to the current item page

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#836]
Idea from here: https://app.element.io/#/room/#eikek_docspell:gitter.im/$7WLBtLEJXWjxqY4C0h1fh_5ZKsNSdrJwbhEYUWzwsM8

A qr code can be shown quite easily within the ui as a svg.

**Comment by monnypython** [comment]
Idea for functionality: Show simple  icon in card like company, for example. On click open the QR-image in new browser-tab to print, download, Screenshot.

**Comment by eikek** [comment]
Ah you mean to put it on the item list/card view page? I was thinking to add it to the item detail page. My feeling is that one is not using this very often and so I thought to not add it to the page you look at every time to find things? Otoh it would then be possible to add it to the multi-select feature to be able to show multiple qr codes…

Is it needed to open it in a new page? I'm using firefox and there is a very neat screenshot feature that lets you select an element on the page to screenshot. Or some external screenshot tool could be used? But maybe it's more convenient to open a new page and print it from the browser?

Another thought is: should it be the url to the single attachment or the whole item? I'd say the latter fits more often…

**Comment by monnypython** [comment]
Ok, since the function probably only needs to be viewed a little per document, it makes sense to place the QR code in the detail area of the item.
... No you are right. It is not necessary to open a new tab if the code can be displayed in the current item. It was just a first thought.
I disagree on your last point though;). In my personal use case, I need the QR code on site to see the corresponding document. E.g. an operating manual for a device. So it's about the info of the document, not the metadata.
There could be an option where you can set whether the link should lead to the item or the document, right? The question then is, of course, to which document, in the case of an item with multiple documents, the link should lead. In that case, when setting the option and several attachments, you could have the desired document selected.

**Comment by eikek** [comment]
Thanks for your feedback! Sounds good to me; I think we might just have both variants (regarding the last point). I start with adding a button to the detail view that opens the QR code for the link to the item page and one button(or menu entry) to each attachment that opens the QR code to this attachment. Then you can simply choose which link you want the QR code for. wdyt?

**Comment by monnypython** [comment]
I agree with you in all points! That sounds very good.
