### ISSUE TITLE
Error "Foreign key constraint is incorrectly formed" upgrading to 0.23.0

### ISSUE THREAD

**Issue by aelsenaar** [eikek/docspell#839]
During the upgrade to version 0.23.0 I get the following error message:

```
Migration V1.23.0__clientsettings.sql failed
--------------------------------------------
SQL State  : HY000
Error Code : 1005
Message    : (conn=763) Can't create table `docspell`.`client_settings` (errno: 150 "Foreign key constraint is incorrectly formed")
Location   : db/migration/mariadb/V1.23.0__clientsettings.sql (/file:/opt/docspell-restserver/lib/com.github.eikek.docspell-store-0.23.0.jar!/db/migration/mariadb/V1.23.0__clientsettings.sql)
Line       : 1
Statement  : CREATE TABLE `client_settings` (
  `id` varchar(254) not null primary key,
  `client_id` varchar(254) not null,
  `user_id` varchar(254) not null,
  `settings_data` longtext not null,
  `created` timestamp not null,
  `updated` timestamp not null,
  foreign key (`user_id`) references `user_`(`uid`) on delete cascade,
  unique (`client_id`, `user_id`)
)
```
When checking the MariaDB logging I get the following extra information:

```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
2021-05-30 08:45:26 0x7f2fc04ff700 Error in foreign key constraint of table `docspell`.`client_settings`:
foreign key (`user_id`) references `user_`(`uid`) on delete cascade,
  unique (`client_id`, `user_id`)
):
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
Please refer to https://mariadb.com/kb/en/library/foreign-keys/ for correct foreign key definition.
Create  table `docspell`.`client_settings` with foreign key constraint failed. Field type or character set for column 'user_id' does not mach referenced column 'uid' near 'foreign key (`user_id`) references `user_`(`uid`) on delete cascade,
  unique (`client_id`, `user_id`)
)'.
```

What can I do to solve this problem? Thx in advance.

**Comment by aelsenaar** [comment]
Is there something wrong with my database setings (e.g. character set or collate)?

It is defined as:
```
CREATE DATABASE IF NOT EXISTS `docspell` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
```

And the user_ table is defined as:

```
CREATE TABLE `user_` (
  `uid` varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL,
  `login` varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cid` varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL,
  `state` varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(254) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logincount` int(11) NOT NULL,
  `lastlogin` timestamp NULL DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by eikek** [comment]
That is really strange to me. What version of MariaDB do you have? I tested it on 10.4.17. The same foreign key has been used before (like in changeset `V1.5.0__userimap.sql`) only without the on delete clause. But it seems to complain about the unique index… I need to look into it a bit more tonight. thanks for teh details. i should be able to reproduce it

**Comment by aelsenaar** [comment]
The version of my MariaDB is 10.4.19.

Alexander

**Comment by eikek** [comment]
>  Field type or character set for column 'user_id' does not mach referenced column 'uid' 
it seems that the field type doesn't match. I suspect the different collate settings. I'm not sure how these collate settings got into the `user_` table. Did you maybe change some db settings recently? 

Could you try to add the same settings as in `uid` column of `user_` to the `user_id` column in `clientsettings`? Simply run the create table statement manually.

**Comment by aelsenaar** [comment]
> Could you try to add the same settings as in uid column of user_ to the user_id column in clientsettings? Simply run the create table statement manually.

I the following statement was executed successfull:

```
CREATE TABLE `client_settings` (
  `id` varchar(254) not null primary key,
  `client_id` varchar(254) not null,
  `user_id` varchar(254) COLLATE utf8mb4_unicode_ci not null,
  `settings_data` longtext not null,
  `created` timestamp not null,
  `updated` timestamp not null,
  foreign key (`user_id`) references `user_`(`uid`) on delete cascade,
  unique (`client_id`, `user_id`)
)
```

Mmm, indeed it looks like it has something to do with the collate settings. I had to migrate from MySQL to MariaDB. (MySQL was not supported) Maybe something went wrong there? I never (intentionally) changed some database and/or table settings. But maybe the SQL export/import messed something up? What are the correct collate setting I should use?

**Comment by eikek** [comment]
Ah  that makes sense, it probably came from the mysql->mariadb migration. The right collate "depends", I'd say.  The `utf8mb4` says to use the 4 byte encoding for characters that allows characters outside the BMP (I'm giessing the `ci` means case insensitive) - I think this is a good default in almost all cases when using unicode or some characters cannot be represented. I don't know Swedish, but I can imagine the BMP is not sufficient to represent all characters. But for ids, this is not important. Docspell uses nothing outside plain ascii for identifiers. You could use a different collate setting for identifiers that could go with a bit less storage. It only is important to use the same for all columns, otherwise mariadb cannot compare these values (I think this resulted in the error). The `utf8mb4` setting makes sense on columns containing "real" text, like those that have `longtext` (as in `attachmentmeta` table).

So to solve this you could remove/change the collate setting from all id columns (I don't know how, probably via MODIFY COLUMN) and then start docspell as before. This could be tedious…, but I recommend it, because the `ci` (case insensitive) setting is not a good idea for identifiers. The other way is to leave it like it is and add a row to `flyway_schema_history` so that docspell thinks this changset has been applied (I could help you with that).

**Comment by aelsenaar** [comment]
Hi, thanks for the info.

I solved it another way. I created a new empty docspell database and let Docspell repopulate the tables/indexes. After that, I exported and imported ONLY the data. That seems to work fine. Now there are no specific collate settings on the columns.

**Comment by eikek** [comment]
Great idea! I forgot about that option entirely
