### ISSUE TITLE
[Feature] More generic notification system

### ISSUE THREAD

**Issue by mikedolx** [eikek/docspell#848]
Hi,

i'd like to know if it would be difficult to implement more generic notifications. Currently it's only possible to send a notification, when a due date expired. For me it would be interesting if the system could send an email as soon as i tag a document with a specific tag. 
I use docspell to manage bills. I'd like to send out a notification, when I have "processed" a bill by adding a tag "paid".

**Comment by eikek** [comment]
Hi @mikedolx, I actually started to think about this recently. I setup my own gotify instance some weeks ago - and was thinking since then about adding notifications, e.g. when a file has been processed…. 

To understand your need: you want a notification email, whenever a certain tag has been added? Wouldn't this maybe run quite many notifications (like you can remove and add tags, or add the same tag to many items in a row)?
I think adding this is some work, when wanting a more generic form (allow different event types, different notification channels, like email or http push etc). It might not be so much when just extending the current form: run a query periodically, if that returns some results then send them. I think this could be a good start. A first attempt is to use the now existing query language to be able to specify any query to run periodically and a template for the message.

I think this is a nice addition and not getting in the way for those who don't need it. As with many other features, it will be a while until it is worked on.

**Comment by mikedolx** [comment]
Hi @eikek ,

> you want a notification email, whenever a certain tag has been added?
Yes, that might trigger a lot of Notifications - you're right. It might be ok for me to send the notifications on a daily base or something. It doesn't have to be an immediate notification from my point of view. I just want to inform my "stakeholder" that i've been working or that i have processed a document.

**Comment by eikek** [comment]
Thanks for your feedback! I think then the "easy" approach might already be useful. It would be possible to have a query like `tag:paid created>{{lastrun}}` or similar (select items with `paid` tag created after the last run). Then it could be setup to run every 8 hours or so….

**Comment by mikedolx** [comment]
just for the record. I used n8n for that particular purpose. In contrast to the original request i use my matrix-server and not E-Mail to get me notified about "unpaid" bills 😁
