### ISSUE TITLE
Adding a further pdf to an existing item leads to "Preview not available"

### ISSUE THREAD

**Issue by lopiuh** [eikek/docspell#910]
Hi,

is reproducable on my side: Adding a new pdf to an existing document, and then switching to the new document leads to "Preview not available" shown instead of a preview thumbnail. Any idea?

Thanks

lopiuh

**Comment by eikek** [comment]
I think this might be related to #348 - the processing and preview generation takes some time. Until the preview is generated, the "preview not available" placeholder image is shown.

If you wait until processing is done (you can watch the "processing queue" page) and then refresh the page, the preview should appear (you might need to hard-reload due to browser caching…).

**Comment by lopiuh** [comment]
I need some time till I can  test it, I come back to it soon.

**Comment by eikek** [comment]
Sure, no worries!

**Comment by lopiuh** [comment]
Hi, it is not fixed (still no thumbnail) MAYBE it is because of the http 404 of the SOLR problem, so that the thumbnailing task is not fired because of a ocr/SOLR error...

**Comment by eikek** [comment]
This could be; at least I could not reproduce it here the last time I tried. I fixed the SOLR error (see last comments #909) - did this work for you? I also think it would be good to solve the solr problem first so we don't hunt down too many subsequent errors. (While it is still interesting, I need to manage priorities due to time constraints :))

**Comment by lopiuh** [comment]
solved, thanks problem is gone after solr worked
