### ISSUE TITLE
Minorbug: "originalfilename" contains suffix filename".converted".pdf

### ISSUE THREAD

**Issue by lopiuh** [eikek/docspell#930]
Hi,

I suppose the filename containing ".converted" is an interim filename and it is not intended that the substring ".converted" is saved as originial filename

![foo](https://user-images.githubusercontent.com/24194715/125168338-68db7b80-e1a5-11eb-9274-60b23af237c5.png)

Greets

lopiuh

**Comment by eikek** [comment]
Hi @lopiuh , this is intended, because docspell converts every file into a pdf. Even pdfs are converted into pdfs again; so the filename indicates that this is not the original file. But you can omit this part in the filename by a config value. See the reference config [here](https://docspell.org/docs/configure/#joex) and look for `converted-filename-part`. It is set by default to `converted` but can be set to an empty string.

**Comment by lopiuh** [comment]
Hi cool, thanks for clearing up,

Greetings

lopiuh
