### ISSUE TITLE
Display active filters somewhere

### ISSUE THREAD

**Issue by floli** [eikek/docspell#966]
Given the many attributes (tag, correspondent, concerning, date, source, ...) I sometimes become lost which filters are active right now, especially when the tree on the left has the active filters collapsed.

It would be helpful to somewhere list the currently active filters. Maybe right of "N documents" at the top would be a good place.

An alternative approach would be to modify the categories on the left (Tags, Tag Categories, ...) if they participate in filtering (change color, add a mark, ...)

Thanks!

**Comment by eikek** [comment]
Yes you're right, this should really be improved. Thanks for reporting! Maybe the simplest option is to somehow mark the menu entries on the left that are active.

**Comment by monnypython** [comment]
I like the idea too.
Maybe something like that ?:

<img src="https://user-images.githubusercontent.com/42573701/128702095-d5309668-f4ba-47e3-9319-f869c40b5784.png" width="400">

**Comment by eikek** [comment]
Yeah, looks good! I'll experiment a little with it. Do you think the yellow frame around the input fields is necessary? I thought to emphasize the headline of each section that has some input.

**Comment by monnypython** [comment]
I guess so. 
In my opinion, the actual filter is the field within the superordinate group.
When I search for documents using the sidebar, I usually unfolded most of the groups, such as "Korrespondent", to see the filter alltogether.
Especially users with many user fields would certainly find it useful to see which fields are contained in the filter.

If you now color the group and field you have covered both working methods:
- colored group -> as @floli says, with collapsed fields
- colored field -> if many fields are opened

You can still discuss whether it is the field frame, the background or the text that is colored.
In order to cover all user-defined field types such as boolean, changing the text would certainly be the most general attribute that works in the whole UI (?).

💭 _Just one idea that came to me while I was writing:_
Perhaps it also makes sense to show an additional button for the filtered groups. So you can also remove all fields inside a specific group.

![image](https://user-images.githubusercontent.com/42573701/128816343-3416c1ad-6a31-449a-a63d-630cfaac5397.png)


---

To capture the other idea from @floli, here is another gimmick (which I find a bit more elegant;):

Here it is enough to simply display the individual search texts because the user can deduce what is meant from the context. The filter is always in view as a whole. No matter what is set in the sidebar.
-> Perhaps you can someday work with icons for the assignment that match the user-defined icons of the fields: D
(Reference: [marix-chat](https://matrix.to/#/!XPBQozyvvbElwZbbOO:gitter.im/$cq-lUqrkfyZR0VpO18vNdex3VP9UrFZ2z6XH2PEtQqg?via=gitter.im&via=wdatrix-.de&))

![image](https://user-images.githubusercontent.com/42573701/128816200-85bc6ce9-bd67-47c9-96bb-62ff61945c41.png)

**Comment by eikek** [comment]
> Especially users with many user fields would certainly find it useful to see which fields are contained in the filter.

I think this is probably not a very common use case. In search view, you would actually only add a field that you want to search for. So every field is used in the query. I'll see how difficult or easy it is and decide then ;-) Currently I like most to change the heading of a section and maybe the icon. I also like the idea of the reset button/icon in the heading of a section.




> Here it is enough to simply display the individual search texts because the user can deduce what is meant from the context. The filter is always in view as a whole. No matter what is set in the sidebar.

Yes, this looks useful. I was also thinking about to make the now "power search" the default and always display the query that is generated from the menu. Not sure if people who are not so much into writiing "queries" would like this, though. But I personally don't like that it is currently the search menu *and* the search query that is applied. But otoh if it is visually indicated which part of the menu is "active" this is already a good help.

**Comment by monnypython** [comment]
> In search view, you would actually only add a field that you want to search for. So every field is used in the query.
That is of course correct. My mistake 😕.

I'm not sure I got that right. You mean I set the filter in the sidebar and the matching query is displayed as a search string in the power search-bar?
Sounds pretty good actually. You could simply "preset" the search using the sidebar and then refine it with the familiar query functions in the "Power Search" bar.
At the moment there is the setting or checkbox for the power search. Perhaps the "generated" string of the query could only be displayed when the power search is activated, and when working via the sidebar (without power search), "only" the coloration of the area headings is available?

**Comment by vakilando** [comment]
> I was also thinking about to make the now "power search" the default and always display the query that is generated from the menu.

This is a very good idea!!!

Another proposal:
It would be cool if the power search would remember and display the last 5 perfomed searches and/or the 5 most used searches

**Comment by eikek** [comment]
> I'm not sure I got that right. You mean I set the filter in the sidebar and the matching query is displayed as a search string in the power search-bar?

Yes exactly. The search menu now composes a query which is send to the server (and possibly enhanced from the search bar).



> Perhaps the "generated" string of the query could only be displayed when the power search is activated, and when working via the sidebar (without power search), "only" the coloration of the area headings is available?

Ah yes, this could work. There are some usability problems still, for example: the search menu uses IDs when searching which is really inconvenient to the user when being rendered in the search bar. I have to take a deeper look  :)



> It would be cool if the power search would remember and display the last 5 perfomed searches and/or the 5 most used searches

Yes, there are some nice features possible with the query. It allows now for bookmarking, maybe a dashboard like home page and stuff like this. I haven't put much thought into it yet, but I want to do this at some point. This would be its own issue then.
